:bug: Topic regular error for the non wildcard configuration
stolostron/multicluster-global-hub pull request #1051
Opened 2024-08-08 09:04 UTC by yanmxa

## Summary

## Related issue(s)

Fixes #https://issues.redhat.com/browse/ACM-13161

2024-08-08 09:30 UTC, hchenxa commented
/assign @clyang82

2024-08-08 12:03 UTC, yanmxa commented
/retest

2024-08-09 02:08 UTC, yanmxa commented
/retest

2024-08-12 01:14 UTC, yanmxa commented
/cc @clyang82

2024-08-12 05:56 UTC, clyang82 commented on test/integration/operator/hubofhubs/transporter_test.go
> +		Skip("skip the ....2")
debug code?

2024-08-12 06:15 UTC, clyang82 requested changes

2024-08-12 06:15 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_kafka_controller.go
> +	if err := r.renderKafkaResources(mgh); err != nil {
I think you may create kafkaResources after `NewStrimziTransporter`

2024-08-12 12:26 UTC, yanmxa commented
/test test-integration

2024-08-12 12:36 UTC, yanmxa commented on test/integration/operator/hubofhubs/transporter_test.go
> +		Skip("skip the ....2")
Rmoved

2024-08-12 14:53 UTC, clyang82 commented
/lgtm

2024-08-12 23:04 UTC, yanmxa commented
e2e setup error, fix this in another PRs

/test test-e2e

2024-08-13 00:46 UTC, yanmxa commented
/test test-integration

2024-08-13 01:32 UTC, yanmxa commented
Verified in the OCP. retrying:
/test test-e2e

2024-08-13 02:52 UTC, clyang82 commented
/lgtm

2024-08-13 02:55 UTC, merged