refactor operator phase 2: component related controller
stolostron/multicluster-global-hub pull request #1189
Opened 2024-10-31 04:58 UTC by ldpliu

## Summary

## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

2024-10-31 11:26 UTC, ldpliu commented
/retest

2024-10-31 11:42 UTC, ldpliu commented
/retest

2024-10-31 13:56 UTC, ldpliu commented
/retest

2024-11-01 00:27 UTC, ldpliu commented
/retest

2024-11-01 07:41 UTC, ldpliu commented
/retest

2024-11-01 08:23 UTC, ldpliu commented
/retest

2024-11-01 08:42 UTC, ldpliu commented
/cc @yanmxa @clyang82

2024-11-04 01:52 UTC, clyang82 requested changes

2024-11-04 01:52 UTC, clyang82 commented on operator/pkg/controllers/meta.go
> +	if mgh == nil {
Suggest to add rbac in each reconcile method so that we know what permissions are needed for this controller.

2024-11-04 01:52 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/controller.go
> +	config            *rest.Config
will it be deleted finally?

2024-11-04 01:52 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/prune/prune_reconciler_test.go
>  	"github.com/stolostron/multicluster-global-hub/operator/pkg/config"
will it be deleted finally?

2024-11-04 04:22 UTC, ldpliu commented on operator/pkg/controllers/meta.go
> +	if mgh == nil {
Done

2024-11-04 04:22 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/prune/prune_reconciler_test.go
>  	"github.com/stolostron/multicluster-global-hub/operator/pkg/config"
yes

2024-11-04 04:22 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/controller.go
> +	config            *rest.Config
yes

2024-11-04 08:29 UTC, clyang82 approved these changes
LGTM

2024-11-04 08:33 UTC, merged