Refactor the addon of global hub operator
stolostron/multicluster-global-hub pull request #1190
Opened 2024-10-31 07:51 UTC by yanmxa

## Summary

## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

2024-11-01 01:23 UTC, yanmxa commented
/test test-unit

2024-11-01 06:42 UTC, yanmxa commented
/cc @clyang82 @ldpliu

2024-11-01 07:00 UTC, clyang82 requested changes

2024-11-01 07:00 UTC, clyang82 commented on operator/pkg/controllers/crd/crd_controller.go
> +	_, err = agent.AddGlobalHubAddonController(ctx, r.Manager,
will it be used to deploy global hub agent?

2024-11-01 07:12 UTC, yanmxa commented on operator/pkg/controllers/agent/default_addon_reconciler.go
> +func AddDefaultAgentReconciler(ctx context.Context, mgr ctrl.Manager) error {
It has been added on the `addon_controller.go` `// +kubebuilder:rbac:groups=cluster.open-cluster-management.io,resources=managedclusters,verbs=get;list;watch`. Beside, why do we need the `create,update, and delete` permission?

2024-11-01 15:46 UTC, yanmxa commented
/test test-e2e

2024-11-04 01:34 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/controller.go
> +	if !agent.ReadyToEnableAddonManager(ctx, r.client) {
We should start it only if ACM resources are ready. Need add `config.IsACMResourceReady` judgement

2024-11-04 01:48 UTC, yanmxa commented on operator/pkg/controllers/hubofhubs/controller.go
> +	if !agent.ReadyToEnableAddonManager(ctx, r.client) {
Done.

2024-11-04 01:59 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/controller.go
> +	if !config.IsACMResourceReady() || !agent.ReadyToEnableAddonManager(ctx, r.client) {
```suggestion
		if config.IsACMResourceReady(){ 
		if agent.ReadyToEnableAddonManager(ctx, r.client) {
		return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
	} else {
		once.Do(func() {
			// start the addon manager
			if err = agent.StartGlobalHubAddonManager(ctx, r.config, r.client, r.operatorConfig); err != nil {
				log.Fatalw("failed to start the lobal hub addon manager")
			}
		})
		// start the addon controllers
		if err = agent.AddDefaultAgentController(ctx, r.mgr); err != nil {
			return ctrl.Result{}, reconcileErr
		}
		if _, err = agent.AddHostedAgentController(r.mgr); err != nil {
			return ctrl.Result{}, reconcileErr
			return ctrl.Result{}, reconcileErr
		}
		}

		if config.GetAddonManager() != nil {
			if reconcileErr = utils.TriggerManagedHubAddons(ctx, r.client, config.GetAddonManager()); reconcileErr != nil {
				return ctrl.Result{}, reconcileErr
			}
		}
	}
	}
	}
```

2024-11-04 02:29 UTC, clyang82 approved these changes
LGTM

2024-11-04 04:36 UTC, merged