use meta to start agent and managedhub controllers
stolostron/multicluster-global-hub pull request #1211
Opened 2024-11-11 08:08 UTC by ldpliu

## Summary

## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

2024-11-12 07:10 UTC, yanmxa commented on operator/pkg/controllers/meta.go
> +	agent.StartDefaultAgentController,
https://github.com/stolostron/multicluster-global-hub/blob/4fc5c1f2a9f79e8802d3e9f789745ae3f7c5c62e/operator/pkg/controllers/hubofhubs/controller.go#L695-L699

You miss the logic to trigger reconcile the addon in the meta.go

2024-11-12 07:18 UTC, ldpliu commented on operator/pkg/controllers/meta.go
> +	agent.StartDefaultAgentController,
> https://github.com/stolostron/multicluster-global-hub/blob/4fc5c1f2a9f79e8802d3e9f789745ae3f7c5c62e/operator/pkg/controllers/hubofhubs/controller.go#L695-L699
> 
> You miss the logic to trigger reconcile the addon in the meta.go

we already added it :
https://github.com/stolostron/multicluster-global-hub/pull/1211/files#diff-9f7d6063a139ba593684a7dd149b487b3decb1a83c9008e8dc45110adaac497aR160

2024-11-12 08:04 UTC, yanmxa commented on operator/pkg/controllers/meta.go
> +	agent.StartHostedAgentController,
Do we need to control the order of the agent controllers, like we need to make sure the addon manager controller is started first, then start the agent controller

2024-11-12 09:02 UTC, ldpliu commented
/cc @clyang82 @yanmxa

2024-11-13 06:18 UTC, clyang82 requested changes

2024-11-13 06:18 UTC, clyang82 commented on operator/pkg/controllers/managedhub/managedhub_controller.go
> +// +kubebuilder:rbac:groups=apiextensions.k8s.io,resources=customresourcedefinitions,verbs=get;list;watch;update
should be managedcluster instead of customresourcedefinitions

2024-11-13 06:18 UTC, clyang82 commented on operator/pkg/controllers/meta.go
> +	agent.StartHostedAgentController,
good point. it is unnecessary to control the order. But we should allow the controller to be started even if the previous controller is failed to start. Does it make sense?

2024-11-13 06:18 UTC, clyang82 commented on operator/cmd/main.go
>  	_, err = crd.AddCRDController(mgr, operatorConfig, kubeClient, globalHubController)
I am fine that do not handle the error since it will be removed eventually.

2024-11-18 03:39 UTC, ldpliu commented
/retest

2024-11-18 04:18 UTC, ldpliu commented on operator/pkg/controllers/managedhub/managedhub_controller.go
> +// +kubebuilder:rbac:groups=apiextensions.k8s.io,resources=customresourcedefinitions,verbs=get;list;watch;update
Done

2024-11-18 04:18 UTC, ldpliu commented on operator/pkg/controllers/meta.go
> +	agent.StartHostedAgentController,
Yes, Changed.

2024-11-18 08:23 UTC, clyang82 approved these changes
LGTM

2024-11-18 08:25 UTC, merged