:seedling: Assert the status of ACM ready with CRD
stolostron/multicluster-global-hub pull request #1212
Opened 2024-11-11 10:13 UTC by yanmxa

## Summary

## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

2024-11-12 01:11 UTC, yanmxa commented
/retest

2024-11-12 12:09 UTC, yanmxa commented
/retest

2024-11-13 01:02 UTC, yanmxa commented
/cc @clyang82 @ldpliu

2024-11-13 02:17 UTC, clyang82 requested changes

2024-11-13 02:17 UTC, clyang82 commented on operator/pkg/controllers/acm/resources.go
> +
we should not need `update` permission for crd.

2024-11-13 02:17 UTC, clyang82 commented on operator/pkg/config/status.go
> +	CONDITION_MESSAGE_ACM_RESOURCE_READY     = "The ACM Resources is ready"
The ACM resources are ready

2024-11-13 02:17 UTC, clyang82 commented on operator/pkg/config/status.go
> +	CONDITION_MESSAGE_ACM_RESOURCE_NOT_READY = "The ACM Resources is not ready, waiting for installing"
Do we expose this message in condition?

2024-11-13 09:28 UTC, yanmxa commented on operator/pkg/controllers/acm/resources.go
> +
done

2024-11-14 01:47 UTC, clyang82 commented
/lgtm

2024-11-14 01:52 UTC, merged