run prune logic in each controllers
stolostron/multicluster-global-hub pull request #1234
Opened 2024-11-18 13:50 UTC by ldpliu

## Summary

## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

2024-11-19 23:49 UTC, ldpliu commented
/retest

2024-11-21 06:23 UTC, clyang82 requested changes

2024-11-21 06:23 UTC, clyang82 commented on operator/pkg/config/transport_config.go
> +	log.Info("Set Transporter Conn")
keep it as the same as others to use Debug.

2024-11-21 06:23 UTC, clyang82 commented on operator/pkg/config/transport_config.go
> +	log.Debugf("Set Transporter Conn: %v", transporterConn != nil)
"Get Transporter Conn"

2024-11-21 06:23 UTC, clyang82 commented on operator/pkg/controllers/acm/resources.go
> +type ACMMetaController struct{}
why do you want to call `ACMMetaController`? a metacontroller acts as a "controller of controllers". We should only have one meta controller which is used to start all other controllers.

2024-11-21 08:56 UTC, ldpliu commented
/retest

2024-11-22 00:47 UTC, ldpliu commented on operator/pkg/config/transport_config.go
> +	log.Info("Set Transporter Conn")
done

2024-11-22 00:47 UTC, ldpliu commented on operator/pkg/config/transport_config.go
> +	log.Debugf("Set Transporter Conn: %v", transporterConn != nil)
done

2024-11-22 00:47 UTC, ldpliu commented on operator/pkg/controllers/acm/resources.go
> +type ACMMetaController struct{}
changed

2024-11-22 00:47 UTC, ldpliu commented on operator/pkg/config/addon_config.go
> +var isAgentRemoved bool
changed the name, it meas if all the addons deleted.

2024-11-22 00:47 UTC, ldpliu commented on operator/pkg/controllers/agent/addon_manager.go
> +type AddonManagerMetaController struct{}
changed the logic

2024-11-22 03:09 UTC, clyang82 commented on operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
> +		err = operatorutils.PruneMetricsResources(ctx, r.c,
I think it should be included in `mgh.DeletionTimestamp` judgement.

2024-11-22 03:38 UTC, merged