set rbac in each controller
stolostron/multicluster-global-hub pull request #1246
Opened 2024-11-25 07:56 UTC by ldpliu

## Summary

## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

2024-11-25 14:37 UTC, ldpliu commented
/retest

2024-11-26 00:35 UTC, ldpliu commented
/cc @clyang82 @yanmxa

2024-11-26 07:37 UTC, clyang82 commented on operator/pkg/controllers/acm/resources.go
>  var ACMResources = sets.NewString(
You need to add `update` permission for mcgh.

2024-11-26 07:44 UTC, clyang82 requested changes

2024-11-26 07:44 UTC, clyang82 commented on operator/pkg/controllers/agent/addon_manager.go
> +// +kubebuilder:rbac:groups=apps.open-cluster-management.io,resources=placementrules,verbs=get;list;update;patch
duplicated

2024-11-26 07:44 UTC, clyang82 commented on operator/pkg/controllers/agent/addon_manager.go
> +// +kubebuilder:rbac:groups="",resources=configmaps,verbs=get;list;watch;create;update;delete
duplicated

2024-11-26 07:44 UTC, clyang82 commented on operator/pkg/controllers/agent/addon_manager.go
> +// +kubebuilder:rbac:groups=policy.open-cluster-management.io,resources=policies,verbs=get;list;patch;update
Why do we add so many permission for addonmanager? I think we do not need to add such permissions since we use workmanager account to apply the manifestwork which has a big permission. Please confirm.

2024-11-26 09:51 UTC, ldpliu commented on operator/pkg/controllers/agent/addon_manager.go
> +// +kubebuilder:rbac:groups=policy.open-cluster-management.io,resources=policies,verbs=get;list;patch;update
It's difficult to test the permission in one controller, but I try to remove the namespace create and delete permission, all things works fine. So I think you are right.

2024-11-27 02:35 UTC, clyang82 approved these changes
LGTM

2024-11-27 02:36 UTC, clyang82 commented
/override ci/prow/sonarcloud

2024-11-27 02:39 UTC, merged