fix watch resources in each controller
stolostron/multicluster-global-hub pull request #1263
Opened 2024-12-04 09:52 UTC by ldpliu

## Summary

## Related issue(s)

Fixes #

## Tests
* [ ] Unit/function tests have been added and incorporated into `make unit-tests`.
* [ ] Integration tests have been added and incorporated into `make integration-test`.
* [ ] E2E tests have been added and incorporated into `make e2e-test-all`.
* [ ] List other manual tests you have done.

2024-12-05 06:28 UTC, ldpliu commented
/test test-integration

2024-12-05 09:18 UTC, ldpliu commented
/cc @clyang82 @yanmxa

2024-12-09 02:49 UTC, clyang82 requested changes

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/backup/backup_start.go
> +
move it after `IsACMResourceReady`

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/grafana/grafana_reconciler.go
> +	log.Info("start grafana controller")
ditto

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/inventory/inventory_reconciler.go
> +
move it after `GetStorageConnection`

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/grafana/grafana_reconciler.go
> +		Watches(&corev1.Service{},
Need to add more permissions for this controller

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/managedhub/managedhub_controller.go
> +
move it after `IsACMResourceReady`

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/manager/manager_reconciler.go
> +		Watches(&rbacv1.RoleBinding{},
add more permissions for this controller

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/storage/storage_reconciler.go
> +			Watches(&promv1.PrometheusRule{},
Does it work when switch enableMetrics from false to true?

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
>  	}
Move it after `startedKafkaController`. Use `Info` for consistence?

2024-12-09 02:49 UTC, clyang82 commented on operator/pkg/controllers/webhook/webhook_controller.go
> +	log.Info("start webhook controller")
move it after `IsACMResourceReady`

2024-12-09 07:25 UTC, ldpliu commented on operator/pkg/controllers/backup/backup_start.go
> +
Done

2024-12-09 07:25 UTC, ldpliu commented on operator/pkg/controllers/grafana/grafana_reconciler.go
> +	log.Info("start grafana controller")
Done

2024-12-09 07:25 UTC, ldpliu commented on operator/pkg/controllers/inventory/inventory_reconciler.go
> +
Done

2024-12-09 07:26 UTC, ldpliu commented on operator/pkg/controllers/grafana/grafana_reconciler.go
> +		Watches(&corev1.Service{},
Done

2024-12-09 07:26 UTC, ldpliu commented on operator/pkg/controllers/managedhub/managedhub_controller.go
> +
Done

2024-12-09 07:26 UTC, ldpliu commented on operator/pkg/controllers/storage/storage_reconciler.go
> +			Watches(&promv1.PrometheusRule{},
wath the resources when crd exist

2024-12-09 07:26 UTC, ldpliu commented on operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
>  	}
Done

2024-12-09 07:27 UTC, ldpliu commented on operator/pkg/controllers/webhook/webhook_controller.go
> +	log.Info("start webhook controller")
Done

2024-12-10 06:56 UTC, clyang82 approved these changes
LGTM

2024-12-10 06:57 UTC, merged