Fixed resources are not add the global hub finalizer in OCM namespace
stolostron/multicluster-global-hub pull request #219
Opened 2022-09-22 13:31 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>
Fixed: https://github.com/stolostron/backlog/issues/25837

2022-09-23 06:54 UTC, yanmxa commented
/retest

2022-09-23 07:24 UTC, yanmxa commented
/cc @clyang82 @morvencao

2022-09-23 09:06 UTC, morvencao commented on manager/pkg/specsyncer/spec2db/controller/controllers_suite_test.go
> +		MetricsBindAddress: ":8083",
specify `MetricsBindAddress: "0"` to disable metrics server in testing, as what I did in https://github.com/stolostron/multicluster-global-hub/pull/223

2022-09-23 09:10 UTC, yanmxa commented on manager/Dockerfile
> +COPY ./operator ./operator/
We need it in the manager.  Because  the manager meed the MGH api which is from operator. Otherwise it will throw error like `no required module provides`

2022-09-26 08:01 UTC, clyang82 requested changes

2022-09-26 08:01 UTC, clyang82 commented on manager/pkg/specsyncer/spec2db/controller/application_spec_sync.go
> +				if kind := reference.Kind; kind == constants.HOHInstanceKind {
who add the ownerreference of MulticlusterGlobalHub for the application?

2022-09-26 09:26 UTC, yanmxa commented on manager/Dockerfile
> +COPY ./operator ./operator/
I havn't figure out the issue. Since we have swith the OwnerReference from MGH to MCH. I have removed the line.

2022-09-26 09:28 UTC, yanmxa commented on manager/pkg/specsyncer/spec2db/controller/application_spec_sync.go
> +				if kind := reference.Kind; kind == constants.HOHInstanceKind {
I misunderstanded the OwnerReference before and I have corrected the right now

2022-09-26 13:12 UTC, clyang82 commented
/lgtm

2022-09-26 13:16 UTC, merged