add OCM prefix for clusterrole and clusterrolebinding
stolostron/multicluster-global-hub pull request #276
Opened 2022-11-03 08:49 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>
Referrence: https://github.com/stolostron/backlog/issues/26271

2022-11-03 09:53 UTC, yanmxa commented
/retest

2022-11-04 01:14 UTC, clyang82 commented on operator/config/rbac/auth_proxy_client_clusterrole.yaml
> +  name: open-cluster-management:metrics-reader
we do not use this role. @morvencao right?

2022-11-04 02:22 UTC, morvencao commented on operator/config/rbac/auth_proxy_client_clusterrole.yaml
> +  name: open-cluster-management:metrics-reader
correct, we will never use this role, so no need to update it. @yanmxa

2022-11-04 02:25 UTC, morvencao requested changes
@yanmxa I think we don't add prefix to the role/clusterrole/rolebing/clusterrolebinding to the operator, because they will be installed with OLM, the csv will help to generate the names. We should focus on role/clusterrole/rolebing/clusterrolebinding for manager and agent? right? @clyang82

2022-11-04 02:28 UTC, yanmxa commented on operator/config/rbac/auth_proxy_client_clusterrole.yaml
> +  name: open-cluster-management:metrics-reader
Yes, I haven't seen this `clusterrole` is bound to any object. And I will remove it

2022-11-04 02:28 UTC, morvencao reviewed
Also I think you missed role and rolebinding for agent in hosted mode.

2022-11-04 02:33 UTC, yanmxa commented
> Also I think you missed role and rolebinding for agent in hosted mode.

Maybe we just need to add the `open-cluster-management` to the `clusterrole` and `clusterrolebinding`.  Cause role and rolbinding is namespaced. We don't need a prefix to indicate where it's from. 

Am I right? @clyang82 @morvencao

2022-11-04 02:36 UTC, yanmxa commented
> @yanmxa I think we don't add prefix to the role/clusterrole/rolebing/clusterrolebinding to the operator, because they will be installed with OLM, the csv will help to generate the names. We should focus on role/clusterrole/rolebing/clusterrolebinding for manager and agent? right? @clyang82

Agree!

2022-11-04 02:49 UTC, morvencao commented
OK @yanmxa make sense to me! thanks.

2022-11-04 03:17 UTC, morvencao commented on operator/config/rbac/auth_proxy_client_clusterrole.yaml
> -  - get
Let's keep it for future usage.

2022-11-04 03:21 UTC, yanmxa commented on operator/config/rbac/auth_proxy_client_clusterrole.yaml
> -  - get
Okay. I rollback the role.

2022-11-04 05:42 UTC, morvencao approved these changes
/lgtm

2022-11-04 10:09 UTC, merged