add high scale simulation docs
stolostron/multicluster-global-hub pull request #326
Opened 2023-02-24 15:35 UTC by yanmxa

Signed-off-by: myan [myan@redhat.com](mailto:myan@redhat.com)

2023-02-24 15:36 UTC, nirrozenbaum commented on test/simulation/README.md
> +![Sale Test Environment](doc/architecture/scale-tests-environment-arch.png)
typo, Scale

2023-02-24 15:39 UTC, nirrozenbaum commented on test/simulation/README.md
> +So far we have a Regional Hub, but how do we use it to simulate a large scale cluster? Since the transport status path is very sensitive to performance issues, and is the bottleneck that affects scal
I wouldn't say that transport status path is the bottleneck.
the real bottleneck is the db.
it would be correct to say that the status path represents scale larger then spec path, and therefore we simulate this path.

2023-02-25 00:38 UTC, yanmxa commented on test/simulation/README.md
> +So far we have a Regional Hub, but how do we use it to simulate a large scale cluster? Since the transport status path is very sensitive to performance issues, and is the bottleneck that affects scal
Thank you @nirrozenbaum! I corrected the description.

2023-02-28 01:10 UTC, clyang82 requested changes

2023-02-28 01:10 UTC, clyang82 commented on doc/simulation/README.md
> +- Simulate the global hub agent by changing the `leafHubName` when sends messages to the global hub manager(status path). [the snippet](https://github.com/stolostron/leaf-hub-status-sync/blob/51cffef
Does it mean that there are 1000 managed clusters with the same name in db? but share the different regional hub name.

2023-02-28 01:10 UTC, clyang82 commented on doc/simulation/README.md
> +we connect global hub manager to agent(e.g., 1000 agents connect around the same time). We test it by running SQL query using `COUNT` and verify we have the expected MCs and polices in the database.
> polices

typo - policies

2023-02-28 01:10 UTC, clyang82 commented on doc/simulation/README.md
> +We provide a [count script](cluster-stopwatch.sh) for the cluster, if you want to count polices, just change the `status.managed_clusters` to `status.compliance`. Welcome you to optimize and enhance
> polices

nit

2023-02-28 02:31 UTC, yanmxa commented on doc/simulation/README.md
> +Basically we need **two REAL clusters**, one that serves as global hub, and the other serve as reginal hub with agent. In the single regional hub, we use the [CLC simulator](https://github.com/hanqiu
Yes, two Openshift clusters

2023-02-28 02:35 UTC, yanmxa commented on doc/simulation/README.md
> +- Simulate the global hub agent by changing the `leafHubName` when sends messages to the global hub manager(status path). [the snippet](https://github.com/stolostron/leaf-hub-status-sync/blob/51cffef
Yes,  1000 managed clusters, with 100 different regional hub names, it will create 10 K records in the `status.managed_cluster` table.

2023-02-28 05:51 UTC, clyang82 commented
/lgtm

2023-02-28 05:55 UTC, merged