expose image configs by mulitcluster-global-hub-operator environment
stolostron/multicluster-global-hub pull request #361
Opened 2023-03-23 02:15 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>

2023-03-23 03:56 UTC, yanmxa commented
/retest

2023-03-23 07:13 UTC, yanmxa commented
/test test-e2e

2023-03-23 09:41 UTC, yanmxa commented
/retest

2023-03-23 10:37 UTC, yanmxa commented
/retest

2023-03-24 06:11 UTC, morvencao commented on operator/pkg/config/multiclusterglobalhub_config.go
> +
it's weird to put image pull secret and pull policy in the image override map.

2023-03-24 09:02 UTC, yanmxa commented on operator/pkg/config/multiclusterglobalhub_config.go
> +
It seems that it is not so clear, and I changed it to get the pull policy and secret directly from mgh CR.

2023-03-24 09:22 UTC, yanmxa commented
/retest

2023-03-27 04:08 UTC, yanmxa commented
/cc @clyang82 @morvencao

2023-03-27 06:10 UTC, clyang82 requested changes

2023-03-27 06:10 UTC, clyang82 commented on operator/pkg/controllers/addon/addon.go
> +	if len(mgh.Spec.ImagePullSecret) > 0 {
Get the `imagePullSecret` value from mch if not setting obviously. WDYT?

2023-03-27 07:38 UTC, yanmxa commented on operator/pkg/controllers/addon/addon.go
> +	if len(mgh.Spec.ImagePullSecret) > 0 {
@clyang82 
Of course, I think we can set the secret according to the priority.
1. The secret set by MCGH CR
2. Using the default secret `multiclusterhub-operator-pull-secret`
3. Using the user's default pull secret, that is to say both 1 and 2 are empty

2023-03-27 14:02 UTC, clyang82 requested changes

2023-03-27 14:02 UTC, clyang82 commented on operator/pkg/config/multiclusterglobalhub_config.go
> +// GetImagePullSecret returns the image pull secret name and data
I think it is a little complex here. You have designed this func `GetImagePullSecret` to return the imagepullsecret name and imagepullsecret data. Actually, we only need to retrieve the imagepullsecret to create in mc side by using manifestwork. we do not need to call this func in deploying grafana, manager, etc.

I think the ideal way is to get the imagepullsecret name from the mcgh always. if user sets the imagepullsecret, then use it. if user does not set the imagepullsecret, we set the default value. in other words, you can always get the correct imagepullsecret name from mcgh.

We only need to retrieve the imagepullsecret secret when the agent is enabled. the previous code can be reusable. hope it helps.

2023-03-28 01:37 UTC, yanmxa commented on operator/pkg/config/multiclusterglobalhub_config.go
> +// GetImagePullSecret returns the image pull secret name and data
This function is used to validate whether the secrets exist. Since you mean that the manager and grafana don't need to verify the secret has been created. I just keep this validation in the addon.

2023-03-28 06:14 UTC, clyang82 requested changes
Please add imagePullSecret in `mch` https://github.com/stolostron/multicluster-global-hub/blob/2691a03a03a2fcefd82c7c184eec06a67ae2d1c2/operator/pkg/controllers/addon/manifests/templates/hubcluster/hubcluster-mch.yaml#L13  It is used to use this imagepullsecret to download acm images.

2023-03-28 06:20 UTC, yanmxa commented
> 

Done.

2023-03-28 06:24 UTC, yanmxa commented on operator/pkg/config/multiclusterglobalhub_config.go
> +			imagePullSecretName = operatorconstants.DefaultImagePullSecretName
This should be `imagePullSecret.GetName()`. the default image is an error.

2023-03-28 06:26 UTC, clyang82 approved these changes
/lgtm

2023-03-28 08:16 UTC, merged