retry to sync the local compliance data if failed
stolostron/multicluster-global-hub pull request #408
Opened 2023-05-04 03:42 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>
- add a retry data mechanism for the grafana dashboard.
- add the cronjob scheduler to the controller runtime manager to support HA
- add log for the cronjob goroutine.

2023-05-04 04:19 UTC, yanmxa commented
/retest

2023-05-04 04:53 UTC, yanmxa commented
/test test-e2e

2023-05-04 06:12 UTC, clyang82 requested changes

2023-05-04 06:12 UTC, clyang82 commented on manager/Dockerfile
> +FROM registry.ci.openshift.org/stolostron/builder:go1.20-linux AS builder
Do we have this base image?

2023-05-04 06:12 UTC, clyang82 commented on manager/pkg/cronjob/task/compliance_history.go
> +			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
Please rename the column from `update_at` to `compliance_date` in `local_status.compliance_history`. it indicates the data is for last day. the Format is `MM-DD-YYYY` without anytime since it is daily level.

2023-05-04 06:39 UTC, yanmxa commented on manager/Dockerfile
> +FROM registry.ci.openshift.org/stolostron/builder:go1.20-linux AS builder
@clyang82 Yes, we have.

2023-05-04 06:50 UTC, clyang82 commented on manager/Dockerfile
> +FROM registry.ci.openshift.org/stolostron/builder:go1.20-linux AS builder
then we need to update go.mod to use 1.20 as well. I am not sure if we really need to do it. Did you try with [gocron](https://github.com/go-co-op/gocron) 1.20?

2023-05-04 07:14 UTC, yanmxa commented on manager/pkg/cronjob/task/compliance_history.go
> +			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
@clyang82 Sure!
I have added the column `compliance_date DATE DEFAULT (CURRENT_DATE - INTERVAL '1 day') NOT NULL, 
` in the `local_status.compliance_history`. But the date format of a date column is not specified within the column definition. However, you can control the display format of the date when querying the table by the `to_char` function.

For example, to display the `compliance_date` column in the format `"MM-DD-YYYY"`, you can use the following qury:
```sql
SELECT id, cluster_id, to_char(compliance_date, 'MM-DD-YYYY'), compliance, compliance_changed_frequency
FROM local_status.compliance_history;
```

2023-05-04 07:36 UTC, yanmxa commented on manager/Dockerfile
> +FROM registry.ci.openshift.org/stolostron/builder:go1.20-linux AS builder
I have tested the following case:

1. with go1.18 and gocron v1.18.0, then we can build image `make build-manager-image`. but the `LastRun` issue appeared as we discussed.
2. with go1.18 and gocron v1.20.0, then we can build image `make build-manager-image`. but the `LastRun` issue appeared as we discussed.
3. with go1.18 and the latest version gocron v1.23.0, then it appears the follwing error when build the global hub manager image
    ```bash
    $ make build-manger-image
    ...
    /go/pkg/mod/github.com/go-co-op/gocron@v1.23.0/executor.go:60:34: undefined: atomic.Int64
    /go/pkg/mod/github.com/go-co-op/gocron@v1.23.0/executor.go:60:34: too many errors
    note: module requires Go 1.20
    The command '/bin/sh -c go build -o bin/manager ./manager/cmd/manager/main.go' returned a non-zero code: 2
    make: *** [Makefile:38: build-manager-image] Error 2
    ```
4. with go1.20 and the latest version gocron v1.23.0, then it can build the image and the `LastRun` log issue disappear.

2023-05-04 07:38 UTC, yanmxa commented
/test test-unit

2023-05-04 07:45 UTC, yanmxa commented
/test test-unit

2023-05-04 08:04 UTC, yanmxa commented
/test test-unit

2023-05-04 08:43 UTC, yanmxa commented on manager/Dockerfile
> +FROM registry.ci.openshift.org/stolostron/builder:go1.20-linux AS builder
```bash
 kubectl exec -it $(kubectl get pods -n hoh-postgres -l postgres-operator.crunchydata.com/role=master -o jsonpath='{.items..metadata.name}') -c database -n hoh-postgres -- psql -U postgres -d hoh -c "select * from $table"
                  id                  |              cluster_id              |         updated_at         | compliance_date |  compliance   | compliance_changed_frequency
--------------------------------------+--------------------------------------+----------------------------+-----------------+---------------+------------------------------
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:06:50.361935 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:13:30.834554 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:18:30.825338 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:23:30.827387 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:29:18.407302 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:30:18.407678 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:31:18.406608 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:32:18.406933 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:33:18.407279 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:34:18.406189 | 2023-05-03      | non_compliant |                            0

```

2023-05-04 08:43 UTC, yanmxa commented on manager/pkg/cronjob/task/compliance_history.go
> +			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
```bash
 kubectl exec -it $(kubectl get pods -n hoh-postgres -l postgres-operator.crunchydata.com/role=master -o jsonpath='{.items..metadata.name}') -c database -n hoh-postgres -- psql -U postgres -d hoh -c "select * from $table"
                  id                  |              cluster_id              |         updated_at         | compliance_date |  compliance   | compliance_changed_frequency
--------------------------------------+--------------------------------------+----------------------------+-----------------+---------------+------------------------------
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:06:50.361935 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:13:30.834554 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:18:30.825338 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:23:30.827387 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:29:18.407302 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:30:18.407678 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:31:18.406608 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:32:18.406933 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:33:18.407279 | 2023-05-03      | non_compliant |                            0
 597c46ec-1631-4b09-b4fe-011c00f667d2 | 8026f189-55e7-49f0-ad46-57766799d05b | 2023-05-04 07:34:18.406189 | 2023-05-03      | non_compliant |                            0

```

2023-05-04 09:30 UTC, yanmxa commented on manager/Dockerfile
> +FROM registry.ci.openshift.org/stolostron/builder:go1.20-linux AS builder
@clyang82 I replace the go1.18 to go1.19 and it works.

2023-05-04 09:46 UTC, yanmxa commented on manager/pkg/cronjob/task/compliance_history.go
> +			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
@clyang82 Done!

2023-05-04 09:47 UTC, yanmxa commented
/retest

2023-05-04 11:06 UTC, clyang82 commented on manager/Dockerfile
> +FROM registry.ci.openshift.org/stolostron/builder:go1.19-linux AS builder
Need update `go.mod` accordingly. And https://github.com/openshift/release/blob/master/ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main.yaml

2023-05-05 01:29 UTC, yanmxa commented
/retest

2023-05-05 01:56 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/database/3.tables.sql
> +    created_at timestamp without time zone DEFAULT now() NOT NULL,
we may not need `create_at`

2023-05-05 02:02 UTC, yanmxa commented on operator/pkg/controllers/hubofhubs/database/3.tables.sql
> +    created_at timestamp without time zone DEFAULT now() NOT NULL,
Sure, I keep the `created_at` here to track the inserting time of the record for debugging.

2023-05-05 02:06 UTC, yanmxa commented on manager/Dockerfile
> +FROM registry.ci.openshift.org/stolostron/builder:go1.19-linux AS builder
@clyang82 upgrade the other references in [here](https://github.com/stolostron/multicluster-global-hub/pull/410).

2023-05-05 02:08 UTC, yanmxa commented on operator/pkg/controllers/hubofhubs/database/3.tables.sql
> +    created_at timestamp without time zone DEFAULT now() NOT NULL,
@clyang82 Done.

2023-05-05 02:20 UTC, yanmxa commented
/retest

2023-05-05 02:53 UTC, clyang82 approved these changes
LGTM

I will send a PR to update the dashboard to use `compliance_date`  soon.

2023-05-05 02:57 UTC, merged

2023-05-06 00:12 UTC, bjoydeep commented on manager/pkg/cronjob/sheduler.go
> +	scheduler := gocron.NewScheduler(time.Local) // or time.UTC
Can we add some explanation in the code as to why we are switching from UTC to local. For example - 
Clusters can be in different timezones. But we have to align the data for all of them in one tine. Either this can be UTC or it can be local time of GH. If someone is at timezone of GH - a fair assumption for now - it is very strange if we say that our calculated day has changed (because are doing calculation based on UTC)! Therefore  we are choosing local GH time for now. This is something we will have to get more real feedback on.

2023-05-06 00:32 UTC, bjoydeep commented on manager/pkg/cronjob/task/compliance_history.go
> +			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
@yanmxa I think @clyang82 point here is that this table is a `daily` summary. So each row represents status of policy on that cluster for `that day`. So we should make this column a date imho.
Does that make sense?
What you did will work- but will be very confusing.

2023-05-06 00:33 UTC, bjoydeep commented on manager/pkg/cronjob/task/compliance_history.go
> +			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
Sorry, I think you have changed it. Good.

2023-05-06 00:50 UTC, bjoydeep commented on manager/pkg/cronjob/task/compliance_history.go
>  	for offset := 0; offset < int(count); offset += batchSize {
What is the significance of this batchSize/loop here ? I am sure I am missing something..
If we have 5 policies and 10 clusters and each cluster has all the 5 policies, is it ok to say:

1. the local_compliance_view will have 5*10 = 50 rows.
2. so when the for loop is run the 1st time, the offset value is incremented to 0+1000. 
3. Therefore the loop will not be executed again.

2023-05-06 00:57 UTC, bjoydeep commented on manager/pkg/cronjob/task/compliance_history.go
>  	for offset := 0; offset < int(count); offset += batchSize {
I see what you are doing. If batchSize would be set to 10 in the above example -
Then after first loop, the offset would be set to 0+10.
Is there some way we can make this code more readable? Or perhaps just add a comment that this for loop will be only run once if count is less than batch.
Is there any basis of setting batch = 1000? I think this should be a tunable parameter.

2023-05-06 01:00 UTC, bjoydeep commented on manager/pkg/cronjob/task/compliance_history.go
> +			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
BTW this expression definitely has an issue:
```
INSERT INTO local_status.compliance_history (id, cluster_id, compliance) 
			SELECT id,cluster_id,compliance 
			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
```
SELECT..FROM.. LIMIT will not return data in same sequence if executed many time without an order by clause. If you run 
```
SELECT id,cluster_id,compliance 
			FROM local_compliance_view LIMIT 50 offset 50
```
many times, the results will be different. There must be an order by.

2023-05-06 01:09 UTC, bjoydeep commented on manager/pkg/cronjob/task/compliance_history.go
> +		log.Error(err, "create local_compliance_view failed")
This expression will not work:
```
CREATE OR REPLACE VIEW local_compliance_view AS 
		SELECT id,cluster_id,compliance 
		FROM local_status.compliance`)
		
```
Why? Say this job takes 10 min to run. And within this 10 minutes, this data changes. Then our insert into compliance_history will be wrong because this view is really evaluated when syncBatchData is run. Views are evaluated only during run time.
What we should do is create a materialized view. That will really create a snapshot of the data at that point.
We can create this materialized view at inception - when the database is created.
```
CREATE MATERIALIZED VIEW local_compliance_view AS 
		SELECT id,cluster_id,compliance 
		FROM local_status.compliance
```
And then you dont need to drop it anytime. You just need to run a refresh 
```
REFRESH MATERIALIZED VIEW local_compliance_view
```

2023-05-06 01:11 UTC, bjoydeep commented on manager/pkg/cronjob/task/compliance_history.go
> +		return nil
@clyang82 I though we talked about creating a new runtime log table where we will store the results of each nights run.. so that it is persisted. This is a very standard practice when we run nightly jobs. This will help us to come each day and see if the system is running correctly. Container logs roll off - they are not the best to look for.

2023-05-06 01:14 UTC, bjoydeep commented on manager/pkg/cronjob/task/compliance_history.go
> +			FROM local_compliance_view LIMIT $1 OFFSET $2`, batchSize, offset)
And for the order by clause to work fast, we will also need an index on the materialized view.

2023-05-06 01:30 UTC, bjoydeep commented
After this is done, we will have to take another pass at making this really scale. But one step at a time. Want to see this work fully end to end first.

2023-05-07 02:17 UTC, clyang82 commented on manager/pkg/cronjob/task/compliance_history.go
> +		return nil
It will be address by this issue - https://github.com/stolostron/multicluster-global-hub/issues/407