skip reconcile database when all the tables have been initialized
stolostron/multicluster-global-hub pull request #457
Opened 2023-05-30 13:40 UTC by yanmxa

avoid executing all SQL statements to reconcile the database when all the tables have been initialized.

2023-05-31 06:26 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_database.go
> +)
it can be complex to manage the db schema. I can understand that it is cpu wasting reconciler. Can we just do the database reconciler when the controller manager is started whatever the status is? In case, the db table is deleted by accident, it can be recovered after pod starts.

2023-05-31 08:18 UTC, yanmxa commented on operator/pkg/controllers/hubofhubs/globalhub_database.go
> +)
Yes, I will add a status flag to make sure it only reconcile once.

2023-05-31 08:26 UTC, yanmxa commented
/cc @clyang82 @hchenxa @morvencao

2023-05-31 10:05 UTC, morvencao reviewed
this looks good, but we can do better?
 - check the database condition in MGH, if it is true, then skip reconcile database, in that way, we can avoid reconcile database when operator is restarted.

2023-05-31 11:37 UTC, yanmxa commented
> this looks good, but we can do better?
> 
> * check the database condition in MGH, if it is true, then skip reconcile database, in that way, we can avoid reconcile database when operator is restarted.
> 
> Is the database reconcile expected when operator is restarted?

Yes, we expected to reconcile the database when operator is restarted.

2023-05-31 13:17 UTC, clyang82 requested changes

2023-05-31 13:17 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_database.go
> +	if condition.ContainConditionStatus(mgh, condition.CONDITION_TYPE_DATABASE_INIT, condition.CONDITION_STATUS_TRUE) {
move it to the beginning of this reconciler method. if DatabaseReconcileCounter is greater than 0, then return nil. we do not need to get the secrets if we do not need to initiate the db.

2023-06-01 01:01 UTC, yanmxa commented
/retest

2023-06-01 01:22 UTC, clyang82 commented
/lgtm

2023-06-01 01:54 UTC, morvencao reviewed
/lgtm

2023-06-01 01:57 UTC, merged