handle unknown status
stolostron/multicluster-global-hub pull request #461
Opened 2023-05-31 08:04 UTC by ldpliu

https://issues.redhat.com/browse/ACM-5729

2023-05-31 08:04 UTC, ldpliu commented
/cc @clyang82 @hchenxa

2023-05-31 08:24 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
> +              "rawSql": "WITH data as (\n  SELECT\n    ch.compliance_date as \"time\",\n    payload -> 'metadata' -> 'labels' ->> '$label' AS \"$label\",\n    COUNT(CASE WHEN ch.compliance = 'non_com
We have merged a PR yesterday to move table `local_status.compliance_history` to `history.local_compliance`.

2023-05-31 08:35 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
> +              "rawSql": "WITH data as (\n  SELECT\n    ch.compliance_date as \"time\",\n    payload -> 'metadata' -> 'labels' ->> '$label' AS \"$label\",\n    COUNT(CASE WHEN ch.compliance = 'non_com
Changed all places where used this table.

2023-05-31 13:10 UTC, clyang82 requested changes

2023-05-31 13:10 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
> +          "description": "Total number of managed clusters that were  unknown.",
remove the redundant space.

2023-05-31 13:11 UTC, clyang82 commented
BTW, could you append a picture about the changed dashboard?

2023-05-31 13:24 UTC, hchenxa commented
+1 with @clyang82 , a snapshot will be good to let us know the new changes.

2023-06-01 02:46 UTC, ldpliu commented
![fc](https://github.com/stolostron/multicluster-global-hub/assets/56991288/72e06d28-a693-49eb-afca-7e2f24f1bc9a)
![gp](https://github.com/stolostron/multicluster-global-hub/assets/56991288/c1c85db6-0a05-4450-b74c-9ae3cac78d31)

2023-06-01 02:48 UTC, ldpliu commented
@clyang82 @hchenxa I have uploaded the snapshot, please help to review it.

2023-06-01 14:14 UTC, clyang82 approved these changes
LGTM

2023-06-01 15:22 UTC, merged