remove transport/storage secrets from global hub api
stolostron/multicluster-global-hub pull request #468
Opened 2023-06-06 05:13 UTC by yanmxa

Refers: https://issues.redhat.com/browse/ACM-4732

2023-06-06 10:24 UTC, clyang82 requested changes

2023-06-06 10:24 UTC, clyang82 commented on cicd-scripts/run-local-e2e-test.sh
> +database_uri=$(kubectl get secret multicluster-global-hub-storage -n $hub_namespace --kubeconfig ${hub_kubeconfig} -ojsonpath='{.data.database_uri}' | base64 -d)
why do you change the secret name?

2023-06-06 10:24 UTC, clyang82 commented on manager/pkg/statussyncer/syncers_test.go
> +	operatorv1alpha3 "github.com/stolostron/multicluster-global-hub/operator/apis/v1alpha3"
Good point to change it to v1alpha3.

2023-06-06 10:24 UTC, clyang82 commented on operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
> +  relatedImages:
we cannot have the `relatedImages` section. it will break the build.

2023-06-06 10:24 UTC, clyang82 commented on operator/pkg/constants/constants.go
> +)
the previous name is fine for me if we do not concrete reason to change it

2023-06-06 10:24 UTC, clyang82 commented on operator/apis/v1alpha3/multiclusterglobalhub_types.go
> -type KafkaConfig struct {
why do you remove the `KafkaConfig`?

2023-06-06 13:06 UTC, yanmxa commented on operator/apis/v1alpha3/multiclusterglobalhub_types.go
> -type KafkaConfig struct {
The `kafkaConfig` defines two things:
1. the secret `name` which is deprecated after `v1alpha3`
2. the `transportFormat` which I think is a more generic concept than kafka. So it shouldn't be wrapped by the `kafkaConfig`
Based on the above two points, I removed `Kafkaconfig`

2023-06-06 13:24 UTC, yanmxa commented on operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
> +  relatedImages:
It's weird to remove the `relatedImages` after generating the global hub manifests, and I also found the `relatedImages` in the manifest they generated. 
there seems no flag to forbid the `relatedImages`.  Anyway, I can remove it manually.

2023-06-06 13:32 UTC, yanmxa commented on operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
> +  relatedImages:
@clyang82 Done!

2023-06-07 07:49 UTC, clyang82 commented on cicd-scripts/run-local-e2e-test.sh
> +database_uri=$(kubectl get secret multicluster-global-hub-storage -n $hub_namespace --kubeconfig ${hub_kubeconfig} -ojsonpath='{.data.database_uri}' | base64 -d)
that is fine for me

2023-06-07 07:49 UTC, clyang82 commented on operator/apis/v1alpha3/multiclusterglobalhub_types.go
> -type KafkaConfig struct {
for the long term, we may introduce more in `kafkaConfig`. I strongly recommend we keep `kafkaConfig` struct in case we need to have a webhook to transform `transportFormat` into `kafkaConfig`.

2023-06-07 08:05 UTC, yanmxa commented on cicd-scripts/run-local-e2e-test.sh
> +database_uri=$(kubectl get secret multicluster-global-hub-storage -n $hub_namespace --kubeconfig ${hub_kubeconfig} -ojsonpath='{.data.database_uri}' | base64 -d)
So you mean to keep the secret name `storage-secret/transport-secret`?

2023-06-07 09:11 UTC, yanmxa commented on operator/apis/v1alpha3/multiclusterglobalhub_types.go
> -type KafkaConfig struct {
@clyang82 Done!

2023-06-07 09:40 UTC, yanmxa commented
/retest

2023-06-07 09:50 UTC, yanmxa commented
/test test-unit

2023-06-08 05:32 UTC, clyang82 approved these changes
LGTM

2023-06-08 05:33 UTC, clyang82 commented
Please send the following PRs to:
1. update the document to reflect the secret that user needs to prepare
2. watch the secret to fix the ticket @hchenxa logged before.

2023-06-08 05:34 UTC, merged

2023-06-08 06:16 UTC, yanmxa commented
> Please send the following PRs to:
> 
> 1. update the document to reflect the secret that user needs to prepare
> 2. refresh the operator in operatorhub
> 3. watch the secret to fix the ticket @hchenxa logged before.
>    @yanmxa

Sure!