sync the history event from the cluster policy
stolostron/multicluster-global-hub pull request #512
Opened 2023-06-27 13:45 UTC by yanmxa

Refs: https://issues.redhat.com/browse/ACM-5977

2023-06-27 13:47 UTC, yanmxa commented
/hold

2023-06-28 12:18 UTC, yanmxa commented
/unhold

2023-06-28 15:10 UTC, yanmxa commented
/cc @clyang82

2023-06-29 01:52 UTC, clyang82 requested changes

2023-06-29 01:52 UTC, clyang82 commented on agent/pkg/status/bundle/grc/cluster_policy_status_event_bundle.go
> +	if policy.Status.Details == nil {
move it before creating `bundlePolicyStatusEvents`. if `Details` is nil, should not create `bundlePolicyStatusEvents` to save memory.

2023-06-29 01:52 UTC, clyang82 commented on pkg/bundle/status/base_policy_history_event_bundle.go
> +type PolicyStatusEvent struct {
we may share the same struct defined in database/models/event

2023-06-29 01:52 UTC, clyang82 commented on agent/pkg/status/bundle/grc/cluster_policy_status_event_bundle.go
> +					string(rootPolicy.GetUID()), clusterId, bundlePolicyStatusEvents, &modified)
We need to delete the deprecated events from Bundle if it is not in `detail.History`.

2023-06-29 03:31 UTC, yanmxa commented on agent/pkg/status/bundle/grc/cluster_policy_status_event_bundle.go
> +					string(rootPolicy.GetUID()), clusterId, bundlePolicyStatusEvents, &modified)
Done!

2023-06-29 03:31 UTC, yanmxa commented on pkg/bundle/status/base_policy_history_event_bundle.go
> +type PolicyStatusEvent struct {
Done!

2023-06-29 03:31 UTC, yanmxa commented on agent/pkg/status/bundle/grc/cluster_policy_status_event_bundle.go
> +	if policy.Status.Details == nil {
Done!

2023-06-29 05:24 UTC, clyang82 commented
/lgtm

2023-06-29 05:29 UTC, merged