add doc for requirments
stolostron/multicluster-global-hub pull request #516
Opened 2023-06-29 03:51 UTC by ldpliu

2023-06-29 06:04 UTC, ldpliu commented
/cc @clyang82 @hchenxa

2023-06-29 08:13 UTC, ldpliu commented
/cc @yanmxa

2023-06-30 02:43 UTC, clyang82 commented on doc/README.md
> +2. **Crunchy Postgres for Kubernetes** 5.0 or later needs to be installed
`needs to be provided` may be more accurately. we just need to access it.

2023-06-30 02:43 UTC, clyang82 commented on doc/README.md
> +| Outbund to Kafka Cluster | HTTPS | Global hub manager need to get data from Kafak cluster | 443 | IP address of kafka route |
typo. s/kafak/Kafka.

2023-06-30 02:43 UTC, clyang82 commented on doc/README.md
> +    [Learn more details about RHACM](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7)
maybe add another link for ACM size - https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html/install/installing#sizing-your-cluster

2023-06-30 02:43 UTC, clyang82 commented on doc/README.md
> +    [Learn more details about Crunchy Postgres for Kubernetes](https://access.crunchydata.com/documentation/postgres-operator/v5/)
can we point to the size requirement directly?

2023-06-30 05:39 UTC, ldpliu commented on doc/README.md
> +2. **Crunchy Postgres for Kubernetes** 5.0 or later needs to be installed
done

2023-06-30 05:39 UTC, ldpliu commented on doc/README.md
> +| Outbund to Kafka Cluster | HTTPS | Global hub manager need to get data from Kafak cluster | 443 | IP address of kafka route |
done

2023-06-30 05:39 UTC, ldpliu commented on doc/README.md
> +    [Learn more details about RHACM](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7)
done

2023-06-30 05:44 UTC, ldpliu commented on doc/README.md
> +    [Learn more details about Crunchy Postgres for Kubernetes](https://access.crunchydata.com/documentation/postgres-operator/v5/)
> can we point to the size requirement directly?

I can not find any requirement doc for Kafka and Postgre. They only have doc about how to config the requirement like: [Resize Postgre cluster](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/resize-cluster/) or [Config Kafka Resource](https://strimzi.io/docs/operators/latest/configuring.html#con-common-configuration-resources-reference) 
If we need to provide a suggest config, may be we could link to our deploy dir/files like: [Kafka](https://github.com/stolostron/multicluster-global-hub/blob/main/operator/config/samples/transport/kafka-cluster.yaml) and [Postgre](https://github.com/stolostron/multicluster-global-hub/blob/main/operator/config/samples/storage/postgres-cluster/postgres-cluster.yaml)

2023-07-04 03:23 UTC, ldpliu commented on doc/README.md
> +    [Learn more details about Crunchy Postgres for Kubernetes](https://access.crunchydata.com/documentation/postgres-operator/v5/)
> can we point to the size requirement directly?

This is the resources usage in my env. 
![postreq](https://github.com/stolostron/multicluster-global-hub/assets/56991288/655d4ddf-2d59-49d2-a5f5-e1628427f837)
![kafkreq](https://github.com/stolostron/multicluster-global-hub/assets/56991288/47cea776-d2bf-4071-b471-17d277ae9064)


So I provide a Minimum requirements as following:
Postgres: https://github.com/stolostron/multicluster-global-hub/pull/516/files#diff-a0842ea73f3a116eff7958fbf833dd2280c366c0d8985aa05f8e1403e0f39273R86

Kafka: https://github.com/stolostron/multicluster-global-hub/pull/516/files#diff-a0842ea73f3a116eff7958fbf833dd2280c366c0d8985aa05f8e1403e0f39273R103

2023-07-04 06:17 UTC, hchenxa commented on doc/README.md
> +    Global hub manager and grafana services need Postgres database to collect and display data. The data can be accessed by creating a storage secret `storage-secret` in namespace `open-cluster-manag
The secret name is `multicluster-global-hub-storage` now.

2023-07-04 06:17 UTC, hchenxa commented on doc/README.md
> +    > Note: There is a sample script available [here](https://github.com/stolostron/multicluster-global-hub/tree/main/operator/config/samples/storage)(Note:the client version of kubectl must be v1.21
the secret name is `multicluster-global-hub-storage`

2023-07-04 06:18 UTC, hchenxa commented on doc/README.md
> +    **Strimzi** provides a way to run an Kafka cluster on Kubernetes in various deployment configurations.
run a Kafka

2023-07-04 06:19 UTC, hchenxa commented on doc/README.md
> +    So, you need to create a secret `transport-secret` in global hub cluster namespace `open-cluster-management` for the Kafka transport. The secret contains the following fields:
the secret name is `multicluster-global-hub-transport`

2023-07-04 06:19 UTC, hchenxa commented on doc/README.md
> +    > Note: There is a sample script available [here](https://github.com/stolostron/multicluster-global-hub/tree/main/operator/config/samples/transport) to install kafka in `kafka` namespace and crea
the secret name is `multicluster-global-hub-transport`

2023-07-04 06:30 UTC, ldpliu commented on doc/README.md
> +    Global hub manager and grafana services need Postgres database to collect and display data. The data can be accessed by creating a storage secret `storage-secret` in namespace `open-cluster-manag
Thanks, Done

2023-07-04 06:45 UTC, ldpliu commented on doc/README.md
> +    > Note: There is a sample script available [here](https://github.com/stolostron/multicluster-global-hub/tree/main/operator/config/samples/storage)(Note:the client version of kubectl must be v1.21
Done

2023-07-04 06:45 UTC, ldpliu commented on doc/README.md
> +    So, you need to create a secret `transport-secret` in global hub cluster namespace `open-cluster-management` for the Kafka transport. The secret contains the following fields:
done

2023-07-04 06:45 UTC, ldpliu commented on doc/README.md
> +    > Note: There is a sample script available [here](https://github.com/stolostron/multicluster-global-hub/tree/main/operator/config/samples/transport) to install kafka in `kafka` namespace and crea
done

2023-07-04 06:46 UTC, ldpliu commented on doc/README.md
> +    **Strimzi** provides a way to run an Kafka cluster on Kubernetes in various deployment configurations.
done

2023-07-06 09:29 UTC, clyang82 requested changes

2023-07-06 09:29 UTC, clyang82 commented on doc/README.md
> +    | 100m | 2G | 20G |
maybe change 20Gi to 20Gi*3 since there are 3 replicas - https://github.com/stolostron/multicluster-global-hub/blob/main/operator/config/samples/storage/postgres-cluster/postgres-cluster.yaml

2023-07-06 09:29 UTC, clyang82 commented on doc/README.md
> +    | 100m | 8G | 20G |
change to storage size to 60Gi. https://github.com/stolostron/multicluster-global-hub/blob/main/operator/config/samples/transport/kafka-cluster.yaml

2023-07-06 23:41 UTC, bjoydeep commented on doc/README.md
> +    [Learn more details about Crunchy Postgres for Kubernetes](https://access.crunchydata.com/documentation/postgres-operator/v5/)
Should we create a separate section (in this doc itself like @clyang82 suggested) on Sizing and add:
1. PostgreSQL Sizing
1. Kafka Sizing
1. Other microservices - like GH Operator, GH manager etc. (the other pods)

Our Kafka/Postgres sizing are not per pod. Its over all resource consumption. That is fine. But we should probably say what namespaces they are so that it can related. Does that make sense? Example:
| vCPU | Memory | Storage size | namespace|
    | ---- | ------ | ------ |--------|
    | 100m | 2G | 20G | hoh-postgres|

2023-07-06 23:44 UTC, bjoydeep commented on doc/README.md
> +
Does outbound to kafka/postgres matter if they are installed in the cluster? Does our pod use the internal service IP or external route to communicate?

2023-07-06 23:47 UTC, bjoydeep commented on doc/README.md
> +| Outbund to Kafka Cluster | HTTPS | Global hub agent need to sync cluster info and policy info to Kafka cluster | 443 | IP address of kafka route |
In both the tables, lets add the `source address`. Customers have asked for that. 
Example - 
for `Regional hub networking requirements` they need to know where do the pods that need to kafka run on . That is where does the GH Agent pod run. This is needed to set up the Firewall rules. BTW does it support taint/toleration like all other Hub components?

2023-07-06 23:48 UTC, bjoydeep commented on doc/README.md
> +    [Learn more details about RHACM](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7)
Our rhacm sizing section is not good :( .

2023-07-06 23:49 UTC, bjoydeep commented on doc/README.md
> +| Outbund to Kafka Cluster | HTTPS | Global hub agent need to sync cluster info and policy info to Kafka cluster | 443 | IP address of kafka route |
BTW I like the fact that you have added the sizing and networking section!

2023-07-07 02:04 UTC, clyang82 commented on doc/README.md
> +
kafka needs to be accessed by the regional hub, so that it is exposed via route.
postgres is accessed via service.

2023-07-07 02:06 UTC, clyang82 commented on doc/README.md
> +| Outbund to Kafka Cluster | HTTPS | Global hub agent need to sync cluster info and policy info to Kafka cluster | 443 | IP address of kafka route |
Yes. we support to configure `nodeSelector` and `tolerations` in MCGH CR.

2023-07-07 04:08 UTC, bjoydeep commented on doc/README.md
> +
looks good now. Thanks!

2023-07-07 04:09 UTC, bjoydeep commented on doc/README.md
> +| Outbund to Kafka Cluster | HTTPS | Global hub agent need to sync cluster info and policy info to Kafka cluster | 443 | IP address of kafka route |
Good!

2023-07-07 07:33 UTC, ldpliu commented on doc/README.md
> +    | 100m | 2G | 20G |
Done

2023-07-07 07:34 UTC, ldpliu commented on doc/README.md
> +    | 100m | 8G | 20G |
Done

2023-07-07 07:34 UTC, ldpliu commented on doc/README.md
> +| Outbund to Kafka Cluster | HTTPS | Global hub agent need to sync cluster info and policy info to Kafka cluster | 443 | IP address of kafka route |
Add the source address.
Please take a look again. 
Thank you.

2023-07-07 09:42 UTC, clyang82 requested changes

2023-07-07 09:42 UTC, clyang82 commented on doc/README.md
> +| Outbund to Kafka Cluster | HTTPS | Global hub manager need to get data from Kafka cluster | 443 | multicluster-global-hub-manager-xxx pod | IP address of kafka route |
s/outbund/outbound  typo

If we are talking about using our sample to create kafka, then the destination should be kafka route host. not ip address.
if we also address external kafka, then it can be kafka ip address. Not IP address of kafka route

2023-07-10 08:25 UTC, ldpliu commented on doc/README.md
> +    [Learn more details about Crunchy Postgres for Kubernetes](https://access.crunchydata.com/documentation/postgres-operator/v5/)
I move the Sizing part to a separate section https://github.com/stolostron/multicluster-global-hub/pull/516/files#diff-a0842ea73f3a116eff7958fbf833dd2280c366c0d8985aa05f8e1403e0f39273R106

But I think the "3. Other microservices"  is not necessary. As global hub operator and manager or other related pod do not need too much resources. They are same as other acm controller and addon pods. So I think the [Sizing RHACM](https://github.com/stolostron/multicluster-global-hub/pull/516/files#diff-a0842ea73f3a116eff7958fbf833dd2280c366c0d8985aa05f8e1403e0f39273R107) is enough.

2023-07-11 06:03 UTC, clyang82 commented
/lgtm
/approve

2023-07-11 06:06 UTC, clyang82 commented
/cherry-pick release-2.8

2023-07-11 06:10 UTC, merged