add the document for manually exec the job
stolostron/multicluster-global-hub pull request #530
Opened 2023-07-05 10:02 UTC by yanmxa

This PR resolves: https://github.com/stolostron/multicluster-global-hub/issues/525 

Once the [enhancement](https://github.com/stolostron/multicluster-global-hub/issues/502) is accomplished, The document about manually running the compliance job also needs to be updated

2023-07-05 23:06 UTC, bjoydeep commented
Please do not merge this. I very much like what you did @yanmxa . But would like to review it carefully tonight.

2023-07-05 23:06 UTC, bjoydeep commented
/hold

2023-07-06 09:15 UTC, clyang82 requested changes

2023-07-06 12:20 UTC, yanmxa commented on doc/how_global_hub_works.md
> +    ```sql
Yes, I think we need this.
The first reason is there is a constraint on the table, It will Do Nothing `ON CONFLICT (policy_id, cluster_id, compliance_date) DO NOTHING` when inserting again.
The second reason is that the job is failed, we cannot skip this and assume that there are no mistakes in this step.

2023-07-06 21:15 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +- The second is to update the `history.local_compliance` compliance and frequency of a certain day based on `event.local_policies`.
Small typo:
change `compliance and frequency of a certain day`
to
`compliance and frequency for that day`

2023-07-06 21:31 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +2. Check whether the Materialized View(`history.local_compliance_view_<yyyy_MM_dd>`) exists
Agreed with Chunlin.
Also rephrase this:
`If you find on the dashboard that there is no any compliance information on a certain day, and also find the job failure information of the day after this day`
to
`If you find on the dashboard that there is no any compliance information on a certain day, then find the job failure information of the day after this day`

May be try to break this up into smaller sentences. And give an example by using concrete dates.

2023-07-06 21:34 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +2. Check whether the Materialized View(`history.local_compliance_view_<yyyy_MM_dd>`) exists
BTW Can they do anything if this view does NOT exist? Is there a chance of that happening at all?

2023-07-06 21:37 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +    ```sql
So @yanmxa you are saying that this code above is idempotent and can be run safely because it will not do anything if data is already there? That is - can I run this even when the job has run successfully?

2023-07-06 21:37 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +
Do we have tell what sort of failures may happen and what sort of messages we may get?
One obvious failure is database out of space.

2023-07-06 23:21 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +    Replace `'<yyyy_MM_dd>'` with the date from step 1, and `'<yyyy_MM_dd+1>'` with the day after the date. For example, if `'<yyyy_MM_dd>'` equals `'2023-07-01'`, then `'<yyyy_MM_dd+1>'` equals `'20
These 2 statements can be wrapped in a database procedure with an input parameter - the date. And it could be easily run. WDYT?

2023-07-06 23:23 UTC, bjoydeep commented
@clyang82 @yanmxa struck me while reviewing this - can we keep rolling 4~5 days of the materialized view. This will allow us to be able to get the view we need if we detect this failure 2 days later.

2023-07-07 01:44 UTC, yanmxa commented on doc/how_global_hub_works.md
> +    ```sql
@bjoydeep Correct! It will have no effect if we run this manual summary process on a successful job.

2023-07-07 02:13 UTC, clyang82 commented on doc/how_global_hub_works.md
> +### Run the Summarization Process manually
Maybe `Generate the missed compliance data` is more readable.

2023-07-07 02:26 UTC, yanmxa commented on doc/how_global_hub_works.md
> +    Replace `'<yyyy_MM_dd>'` with the date from step 1, and `'<yyyy_MM_dd+1>'` with the day after the date. For example, if `'<yyyy_MM_dd>'` equals `'2023-07-01'`, then `'<yyyy_MM_dd+1>'` equals `'20
@bjoydeep That's a good idea! I need to verify the SQLs can work properly when wrapping them with a function.

2023-07-07 04:05 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +    ```sql
Thanks.

2023-07-07 04:06 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +    Replace `'<yyyy_MM_dd>'` with the date from step 1, and `'<yyyy_MM_dd+1>'` with the day after the date. For example, if `'<yyyy_MM_dd>'` equals `'2023-07-01'`, then `'<yyyy_MM_dd+1>'` equals `'20
Good. Thanks

2023-07-07 04:18 UTC, bjoydeep commented on doc/how_global_hub_works.md
> +
Thanks! looks good

2023-07-07 04:53 UTC, yanmxa commented on doc/how_global_hub_works.md
> +2. Check whether the Materialized View(`history.local_compliance_view_<yyyy_MM_dd>`) exists
Just as in our discussion, I will add another restore path for history compliance when the view does not exist.

2023-07-07 08:45 UTC, yanmxa commented on doc/how_global_hub_works.md
> +### Run the Summarization Process manually
I have added an item named `Generate the missed compliance data` in troubleshooting and linked it to here.

2023-07-10 01:47 UTC, clyang82 approved these changes
LGTM

2023-07-10 01:56 UTC, clyang82 commented
/cherry-pick release-2.8

2023-07-10 03:16 UTC, yanmxa commented
/unhold

2023-07-10 03:18 UTC, merged