Upgrade the global operand from v1alpha3 to v1alpha4
stolostron/multicluster-global-hub pull request #576
Opened 2023-08-14 03:13 UTC by yanmxa

2023-08-14 03:15 UTC, yanmxa commented
/test-all

2023-08-14 08:52 UTC, yanmxa commented
/retest

2023-08-14 09:38 UTC, yanmxa commented
/test test-e2e

2023-08-15 02:01 UTC, clyang82 requested changes

2023-08-15 04:43 UTC, yanmxa commented on operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
> -      [
Done.

2023-08-15 04:53 UTC, yanmxa commented
/retest

2023-08-15 06:48 UTC, clyang82 approved these changes

2023-08-15 06:52 UTC, merged