add alert and merged config
stolostron/multicluster-global-hub pull request #590
Opened 2023-08-22 03:24 UTC by ldpliu

2023-08-22 05:51 UTC, ldpliu commented
/retest

2023-08-23 01:01 UTC, ldpliu commented
/retest

2023-08-24 01:10 UTC, ldpliu commented
/retest

2023-08-24 02:39 UTC, ldpliu commented
/retest

2023-08-24 03:06 UTC, ldpliu commented
/test test-unit

2023-08-24 03:17 UTC, ldpliu commented
/retest

2023-08-24 07:33 UTC, ldpliu commented
/cc @clyang82

2023-08-24 08:23 UTC, ldpliu commented
/retest

2023-08-25 01:17 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +func RestartGrafanaPod(ctx context.Context, kubeClient kubernetes.Interface) error {
Does Grafana support auto-reload the updated configmap?

2023-08-25 01:17 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_grafana_test.go
> +func TestMulticlusterGlobalHubReconciler_generateMergedAlertConfigMap(t *testing.T) {
what is different between `TestMulticlusterGlobalHubReconciler_generateMergedAlertConfigMap` and `Test_mergedAlertConfigMap`?
Do we need to have a test for merge customized alert with rules?

2023-08-25 06:47 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +func RestartGrafanaPod(ctx context.Context, kubeClient kubernetes.Interface) error {
Grafana do not support auto-reload configmap.
https://github.com/grafana/agent/issues/2691

2023-08-29 13:57 UTC, ldpliu commented
/retest

2023-08-30 03:25 UTC, ldpliu commented
/retest

2023-08-30 10:22 UTC, ldpliu commented
/retest

2023-09-01 02:13 UTC, clyang82 requested changes

2023-09-01 02:13 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_controller.go
> +	configmappred := predicate.Funcs{
Does the user need add label for the custom configmap? I do think it is user-friendly way. let us handle with the name just like what we have done for secret. Does it make sense?

2023-09-01 02:13 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +	globalhubv1alpha4 "github.com/stolostron/multicluster-global-hub/operator/apis/v1alpha4"
We follow best practices:
```
go-lang packages

third-party packages

internal packages
```

2023-09-01 02:13 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +	alertConfigMapKey = "acm-global-alerting.yaml"
maybe `multicluster-globalhub-alerting`?

2023-09-01 02:13 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +			grafanaIniKey: []byte(string(defaultGrafanaIniSecret.Data[grafanaIniKey]) + "\n" + string(customGrafanaIniSecret.Data[grafanaIniKey])),
Do we need to merge the same configuration? for example: default has `[users]` and custom has `[users]`.

2023-09-01 02:13 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +			grafanaIniKey: []byte(string(defaultGrafanaIniSecret.Data[grafanaIniKey]) + "\n" + string(customGrafanaIniSecret.Data[grafanaIniKey])),
so we may just ignore the customized one once we have in default. otherwise, the grafana cannot be started successfully.

2023-09-04 03:12 UTC, ldpliu commented
/retest

2023-09-04 06:58 UTC, ldpliu commented
/retest

2023-09-04 09:25 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +			grafanaIniKey: []byte(string(defaultGrafanaIniSecret.Data[grafanaIniKey]) + "\n" + string(customGrafanaIniSecret.Data[grafanaIniKey])),
Done

2023-09-04 09:25 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +	alertConfigMapKey = "acm-global-alerting.yaml"
Done

2023-09-04 09:25 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/globalhub_controller.go
> +	configmappred := predicate.Funcs{
Done

2023-09-04 14:03 UTC, merged