Upgrade client-go to v0.26.7 and controller-runtime to v0.15.0
stolostron/multicluster-global-hub pull request #600
Opened 2023-08-25 12:21 UTC by yanmxa

2023-08-25 12:24 UTC, yanmxa commented
Blocked by: https://github.com/stolostron/multiclusterhub-operator/pull/1093

```bash
# github.com/stolostron/multiclusterhub-operator/api/v1
../vendor/github.com/stolostron/multiclusterhub-operator/api/v1/multiclusterhub_webhook.go:108:27: cannot use &MultiClusterHub{} (value of type *MultiClusterHub) as admission.Validator value in variable declaration: *MultiClusterHub does not implement admission.Validator (wrong type for method ValidateCreate)
                have ValidateCreate() error
                want ValidateCreate() (admission.Warnings, error)
make[1]: *** [Makefile:50: lint] Error 1
make[1]: Leaving directory '/root/workspace/hub-of-hubs/agent'
make: *** [Makefile:44: build-agent-image] Error 2
```

2023-08-30 03:17 UTC, yanmxa commented
/retest

2023-08-30 03:39 UTC, yanmxa commented
/retest

2023-08-30 04:28 UTC, yanmxa commented
/retest

2023-08-30 09:25 UTC, yanmxa commented
/retest

2023-08-30 12:33 UTC, clyang82 commented on go.mod
>  replace (
remove all the replace section should pass the tests.

2023-08-30 13:00 UTC, yanmxa commented on go.mod
>  replace (
I have tried to remove the replacement section. But when build the code, it will throw errors like:
```
go vet ./cmd/... ./pkg/...
# k8s.io/client-go/applyconfigurations/meta/v1
../vendor/k8s.io/client-go/applyconfigurations/meta/v1/unstructured.go:64:38: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to proto.NewOpenAPIData
make[1]: *** [Makefile:50: lint] Error 1
make[1]: Leaving directory '/root/workspace/hub-of-hubs/agent'
make: *** [Makefile:44: build-agent-image] Error 2

# github.com/resmoio/kubernetes-event-exporter/pkg/kube
../vendor/github.com/resmoio/kubernetes-event-exporter/pkg/kube/watcher.go:46:27: cannot use watcher (variable of type *EventWatcher) as "k8s.io/client-go/tools/cache".ResourceEventHandler value in argument to informer.AddEventHandler: *EventWatcher does not implement "k8s.io/client-go/tools/cache".ResourceEventHandler (wrong type for method OnAdd)
                have OnAdd(interface{})
                want OnAdd(interface{}, bool)
make[1]: *** [Makefile:50: lint] Error 1
make[1]: Leaving directory '/root/workspace/hub-of-hubs/agent'
make: *** [Makefile:44: build-agent-image] Error 2
```
So at least we should keep the following package
```bash
replace (
        # Compatible with eventexporter
	k8s.io/api => k8s.io/api v0.26.7
	k8s.io/apiserver => k8s.io/apiserver v0.26.7
	k8s.io/client-go => k8s.io/client-go v0.26.7
	k8s.io/component-base => k8s.io/component-base v0.26.7
	# fixed the document error
	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20230530175149-33f04d5d6b58
)
```

2023-08-31 00:41 UTC, yanmxa commented
/retest

2023-08-31 22:58 UTC, yanmxa commented
/retest

2023-09-01 06:01 UTC, clyang82 requested changes

2023-09-01 06:01 UTC, clyang82 commented on manager/pkg/specsyncer/spec2db/controller/placement_spec_sync.go
> +	// placement.Spec.SpreadPolicy = clusterv1beta1.SpreadPolicy{}
we do not need it.

2023-09-01 09:20 UTC, yanmxa commented on cicd-scripts/run-prow-e2e-test.sh
> +echo "Done" > ./done.text
Yes

2023-09-01 09:44 UTC, yanmxa commented on manager/pkg/specsyncer/spec2db/controller/placement_spec_sync.go
> +	// placement.Spec.SpreadPolicy = clusterv1beta1.SpreadPolicy{}
Done

2023-09-01 09:45 UTC, yanmxa commented on manager/pkg/specsyncer/spec2db/controller/placement_spec_sync.go
> +	// placement.Spec.SpreadPolicy = clusterv1beta1.SpreadPolicy{}
@clyang82 You can see that the `kubernetes-event-exporter` is using the `client-go@v0.26.7`
```
github.com/resmoio/kubernetes-event-exporter@v0.0.0-20230804164846-bbcbeeb38571 k8s.io/api@v0.26.7
github.com/resmoio/kubernetes-event-exporter@v0.0.0-20230804164846-bbcbeeb38571 k8s.io/apimachinery@v0.26.7
github.com/resmoio/kubernetes-event-exporter@v0.0.0-20230804164846-bbcbeeb38571 k8s.io/client-go@v0.26.7
github.com/resmoio/kubernetes-event-exporter@v0.0.0-20230804164846-bbcbeeb38571 cloud.google.com/go@v0.107.0
````

2023-09-01 09:46 UTC, yanmxa commented on go.mod
> +	k8s.io/kube-aggregator v0.26.2
Done

2023-09-01 09:50 UTC, yanmxa commented on go.mod
>  replace (
The kubernetes-event-exporter 
```
github.com/resmoio/kubernetes-event-exporter@v0.0.0-20230804164846-bbcbeeb38571 k8s.io/api@v0.26.7
github.com/resmoio/kubernetes-event-exporter@v0.0.0-20230804164846-bbcbeeb38571 k8s.io/apimachinery@v0.26.7
github.com/resmoio/kubernetes-event-exporter@v0.0.0-20230804164846-bbcbeeb38571 k8s.io/client-go@v0.26.7
github.com/resmoio/kubernetes-event-exporter@v0.0.0-20230804164846-bbcbeeb38571 cloud.google.com/go@v0.107.0
```

2023-09-01 11:00 UTC, yanmxa commented
/retest

2023-09-03 03:20 UTC, yanmxa commented
/cc @clyang82

2023-09-04 06:22 UTC, clyang82 approved these changes
LGTM

2023-09-04 06:25 UTC, merged