Scale test for global hub manager
stolostron/multicluster-global-hub pull request #601
Opened 2023-08-28 13:58 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>

2023-08-30 08:20 UTC, yanmxa commented
/hold

2023-09-05 05:18 UTC, yanmxa commented
/retest

2023-09-05 14:24 UTC, yanmxa commented
test ci/prow/test-unit

2023-09-06 01:23 UTC, yanmxa commented
/retest

2023-09-08 06:54 UTC, yanmxa commented
/unhold

2023-09-12 02:04 UTC, clyang82 commented
Append the original thoughts
<img width="814" alt="image" src="https://github.com/stolostron/multicluster-global-hub/assets/7711311/878af88a-de19-4ed1-a720-828c41be5f73">

2023-09-12 07:19 UTC, clyang82 requested changes
can we move the images folder as a sub-folder of simulation?

2023-09-12 07:19 UTC, clyang82 commented on doc/simulation/README.md
> +    kubectl apply --server-side=true --validate=false -f pkg/testdata/crds
what is root dir here?

2023-09-12 07:19 UTC, clyang82 commented on doc/simulation/README.md
> +- Initialize the policy on the above clusters
can we consolidate the scripts to have:
1. setup.sh ( user provide global hub kubeconfig), including create 5 managed hubs with 300 managed cluster per managed hub, import the managed hubs into global hub automatically and create policies
2. start_watch.sh
3. stop_watch.sh

2023-09-12 07:37 UTC, yanmxa commented on doc/simulation/README.md
> +    kubectl apply --server-side=true --validate=false -f pkg/testdata/crds
This is the global hub project, such as:
``` bash
$ ll
total 608
-rw-r--r--   1 yanmeng  staff   233B Mar 14  2023 CODE_OF_CONDUCT.md
-rw-r--r--   1 yanmeng  staff   222B Mar 14  2023 CONTRIBUTING.md
-rw-r--r--   1 yanmeng  staff    11K Mar 14  2023 LICENSE
-rw-r--r--@  1 yanmeng  staff   3.3K Aug  1 09:55 Makefile
-rw-r--r--@  1 yanmeng  staff   157B Aug  1 09:55 OWNERS
-rw-r--r--   1 yanmeng  staff   4.1K Sep  6 23:14 README.md
-rw-r--r--   1 yanmeng  staff   203B Mar 14  2023 SECURITY.md
drwxr-xr-x   8 yanmeng  staff   256B Sep  4 16:44 agent
drwxr-xr-x   5 yanmeng  staff   160B Sep  6 23:14 cicd-scripts
-rw-r--r--   1 yanmeng  staff   5.1K Mar 14  2023 development.md
drwxr-xr-x  19 yanmeng  staff   608B Sep 11 12:46 doc
-rw-r--r--   1 yanmeng  staff    12K Sep  6 23:14 go.mod
-rw-r--r--   1 yanmeng  staff   232K Sep  6 23:14 go.sum
drwxr-xr-x   9 yanmeng  staff   288B Sep  4 16:44 manager
drwxr-xr-x  15 yanmeng  staff   480B Sep  6 23:14 operator
drwxr-xr-x  13 yanmeng  staff   416B Aug  1 09:55 pkg
drwxr-xr-x   7 yanmeng  staff   224B Aug  1 09:55 release-notes
drwxr-xr-x   7 yanmeng  staff   224B Sep  6 23:14 samples
-rw-r--r--@  1 yanmeng  staff   485B Aug  1 09:55 sonar-project.properties
drwxr-xr-x   7 yanmeng  staff   224B Aug  1 09:55 test
drwxr-xr-x@ 17 yanmeng  staff   544B Sep  5 16:04 vendor
```

2023-09-15 01:29 UTC, yanmxa commented
/hold

2023-09-26 07:11 UTC, yanmxa commented
/test sonarcloud

2023-09-27 04:10 UTC, yanmxa commented
/unhold

I still need the find out why the Postgres pods need so much memory when running the test 

And we can proceed with the PR 
/cc @clyang82 @bjoydeep

2023-10-07 07:38 UTC, clyang82 commented
/lgtm

2023-10-07 08:10 UTC, merged