add alert doc
stolostron/multicluster-global-hub pull request #613
Opened 2023-09-05 06:56 UTC by ldpliu

2023-09-05 07:35 UTC, ldpliu commented
/cc @clyang82 @yahliu @hchenxa @yanmxa

2023-09-05 13:58 UTC, yanmxa commented on doc/README.md
> +We have three alerts by default. These alerts are stored in configmap `multicluster-global-hub-default-grafana-config`. They will watch suspicious policies, suspicious clusters compliance status chan
Is this `configmap` located in namespace `multicluster-global-hub` ?

2023-09-06 02:02 UTC, ldpliu commented on doc/README.md
> +We have three alerts by default. These alerts are stored in configmap `multicluster-global-hub-default-grafana-config`. They will watch suspicious policies, suspicious clusters compliance status chan
Yes

2023-09-06 02:03 UTC, ldpliu commented on doc/README.md
> +- A policy was enabled/disabled
> It's easy to reach thousands of policies in an environment. Do you think the rules have performance bottleneck？

We only filter 1 hour data, so it should be ok.

2023-09-06 07:33 UTC, yanmxa commented
Looks good to me.

2023-09-07 07:29 UTC, yahliu commented on doc/README.md
> +Global hub support customize the grafana.ini files. You just need to create a secret named: `multicluster-global-hub-custom-grafana-config` in the `multicluster-global-hub` namespace, and the data ke
suggest to change as "You just need to create a secret, and it must be named `multicluster-global-hub-custom-grafana-config`.

2023-09-07 07:30 UTC, yahliu commented on doc/README.md
> +Global hub support customize the alerting resources which [grafana support](https://grafana.com/docs/grafana/v9.5/alerting/set-up/provision-alerting-resources/file-provisioning/). You just need to cr
same as above, the confimap name must be called `multicluster-global-hub-custom-alerting`.

2023-09-08 08:49 UTC, ldpliu commented on doc/README.md
> +Global hub support customize the alerting resources which [grafana support](https://grafana.com/docs/grafana/v9.5/alerting/set-up/provision-alerting-resources/file-provisioning/). You just need to cr
done

2023-09-12 07:07 UTC, clyang82 requested changes

2023-09-12 07:07 UTC, clyang82 commented on doc/README.md
> +  If this alert rule becomes firing, it means the [Partition job](#Partition-job) failed.
@yanmxa Do we have a manual step to remediate this issue?

2023-09-12 07:07 UTC, clyang82 commented on doc/README.md
> +If you want to delete a default grafana alert rule, you need to create the [Customize Grafana Alerting Resources](#Customize-Grafana-Alerting-Resources) and include the `deleteRules`.
can we show an example to disable all?

2023-09-12 07:07 UTC, clyang82 commented on doc/README.md
> +  multicluster-globalhub-alerting.yaml: |
can we just use `alerting` as key?

2023-09-14 01:40 UTC, yanmxa commented on doc/README.md
> +  If this alert rule becomes firing, it means the [Partition job](#Partition-job) failed.
No, We haven't added the manually deletions and creations for this retention job.

2023-09-14 02:32 UTC, merged