set grafana route url
stolostron/multicluster-global-hub pull request #623
Opened 2023-09-08 03:23 UTC by ldpliu

2023-09-08 05:51 UTC, ldpliu commented
/cc @clyang82

2023-09-11 01:37 UTC, clyang82 requested changes

2023-09-11 01:37 UTC, clyang82 commented on go.mod
>  	github.com/openshift/library-go v0.0.0-20220727134723-6802b30e83ba
Could you upgrade client-go and library-go to the latest version? I am afraid it will have problems in OCP 4.14. so please use the latest version.

2023-09-11 01:37 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +						"localhost",
Can Grafana reload this configuration automatically?

2023-09-12 03:02 UTC, ldpliu commented on go.mod
>  	github.com/openshift/library-go v0.0.0-20220727134723-6802b30e83ba
Done

2023-09-12 03:02 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/globalhub_grafana.go
> +						"localhost",
Grafana can not support auto reload.

2023-09-13 00:53 UTC, clyang82 approved these changes
LGTM

2023-09-13 00:57 UTC, merged