Add annotation to trigger the cronjobs
stolostron/multicluster-global-hub pull request #644
Opened 2023-09-19 07:57 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>

2023-09-21 04:38 UTC, yanmxa commented
/retest

2023-09-21 07:09 UTC, yanmxa commented
/retest

2023-09-22 01:19 UTC, yanmxa commented
/retest

2023-09-23 03:59 UTC, clyang82 commented on manager/cmd/manager/main.go
> +		"the specified jobs(concatenate multiple jobs with ',') runs when the container starts")
Can we not expose in command? expose in command means user can use it. if we expose an env, nobody knows that. I mean that we can add an env in the manager deployment for this purpose. And then use `os.Getenv` to get the value.

2023-09-23 04:00 UTC, clyang82 requested changes
BTW, I just found that the `sheduler.go` file name should be `scheduler.go`.

2023-09-26 06:42 UTC, yanmxa commented on manager/cmd/manager/main.go
> +		"the specified jobs(concatenate multiple jobs with ',') runs when the container starts")
Done.

2023-09-26 07:51 UTC, clyang82 commented on manager/cmd/manager/main.go
> +	launchJobImmediatelyEnv       = "LAUNCH_JOB_IMMEDIATELY"
what is the value of `LAUNCH_JOB_IMMEDIATELY`? in literal, the value should be true or false.

2023-09-26 11:06 UTC, yanmxa commented on manager/cmd/manager/main.go
> +	launchJobImmediatelyEnv       = "LAUNCH_JOB_IMMEDIATELY"
Since we have two jobs, the value is the cronjob name. We can specify the name to launch the job when the container starts.

2023-09-26 12:43 UTC, clyang82 commented on manager/cmd/manager/main.go
> +	launchJobImmediatelyEnv       = "LAUNCH_JOB_IMMEDIATELY"
maybe `launch_job_names`?

2023-09-27 02:52 UTC, yanmxa commented on manager/cmd/manager/main.go
> +	launchJobImmediatelyEnv       = "LAUNCH_JOB_IMMEDIATELY"
Done.

2023-09-27 03:05 UTC, clyang82 reviewed
/lgtm

2023-09-27 03:22 UTC, merged