Prune resource from database when detaching the hub from the global hub
stolostron/multicluster-global-hub pull request #670
Opened 2023-10-10 14:16 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>

2023-10-10 14:16 UTC, yanmxa commented
/hold

2023-10-11 07:12 UTC, yanmxa commented
/unhold

2023-10-11 07:28 UTC, yanmxa commented
/retest

2023-10-11 10:18 UTC, yanmxa commented
/cc @clyang82 @hchenxa

2023-10-12 03:19 UTC, clyang82 requested changes

2023-10-12 03:19 UTC, clyang82 commented on agent/pkg/status/controller/controller_integration_test.go
> +			subscriptionReportsStatusBundle, ok :=
I do not know what code format tool you are using. why format this line?

2023-10-12 03:19 UTC, clyang82 commented on manager/cmd/manager/main.go
> +		"The watching namespace of the controller")
why make changes here? in my understand, the `watch-namespace` is empty so that it watches all namespaces. the manager starts the placement controller or managedcluster controller needs this scope.

2023-10-12 03:19 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/manifests/manager/clusterrole.yaml
> +  - managedclusters
you need to add `// +kubebuilder` in the globalhub_controller.go and then run `make bundle` to generate.

2023-10-12 03:19 UTC, clyang82 commented on manager/pkg/specsyncer/spec2db/controller/managedhub_spec_sync.go
> +// Copyright (c) 2023 Red Hat, Inc.
Can we tackle it in addoninstall controller - https://github.com/stolostron/multicluster-global-hub/blob/ad0caf45b4cb40109e0840c771352ba0bfad5358/operator/pkg/controllers/addon/addoninstall_reconciler.go#L86?

2023-10-12 08:44 UTC, yanmxa commented on operator/pkg/controllers/hubofhubs/manifests/manager/clusterrole.yaml
> +  - managedclusters
The `clusterrole` of the global hub manager is not generated. So we don't need to add the `// +kubebuilder` comment.

2023-10-12 08:45 UTC, yanmxa commented on manager/pkg/specsyncer/spec2db/controller/managedhub_spec_sync.go
> +// Copyright (c) 2023 Red Hat, Inc.
Well, the global hub manager needs to watch the managedcluster to update the database.

2023-10-12 08:47 UTC, yanmxa commented on manager/cmd/manager/main.go
> +		"The watching namespace of the controller")
Rollback the watch namespace part.

2023-10-12 09:51 UTC, yanmxa commented on agent/pkg/status/controller/controller_integration_test.go
> +			subscriptionReportsStatusBundle, ok :=
I have rollback the format. more details about the format setting will be added later.

2023-10-16 02:49 UTC, clyang82 commented
/lgtm

2023-10-16 02:51 UTC, merged