add grafana e2e
stolostron/multicluster-global-hub pull request #699
Opened 2023-10-23 08:24 UTC by ldpliu

2023-10-23 08:24 UTC, ldpliu commented
/hold

2023-10-23 09:25 UTC, ldpliu commented
/retest

2023-10-23 09:29 UTC, ldpliu commented
/retest

2023-10-23 09:49 UTC, ldpliu commented
/retest

2023-10-23 12:56 UTC, ldpliu commented
/retest

2023-10-24 06:57 UTC, ldpliu commented
/retest

2023-10-24 10:27 UTC, ldpliu commented
/cc @clyang82

2023-10-25 07:50 UTC, clyang82 requested changes
Can you confirm the new added cases are performed? Do we need to add `e2e-tests-grafana-resources` in Makefile ?

2023-10-25 07:50 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/integration_test.go
> +					return fmt.Errorf("mghReconciler.MiddlewareConfig.KafkaConnection should be nil")
why need to wrap in `Eventually`. I think it just runs once. Am I missing sth?

2023-10-25 07:50 UTC, clyang82 commented on test/pkg/e2e/grafana_test.go
> +			}, 2*time.Minute, 10*time.Second).ShouldNot(HaveOccurred())
will it spend too long?

2023-10-25 07:50 UTC, clyang82 commented on test/pkg/e2e/grafana_test.go
> +	url := "http://" + poList.Items[0].Status.PodIP + ":3001/api/" + path
Can pod ip be accessed outside?

2023-10-27 00:43 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/integration_test.go
> +					return fmt.Errorf("mghReconciler.MiddlewareConfig.KafkaConnection should be nil")
This part always failed with some conflict error.
like: 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stolostron_multicluster-global-hub/699/pull-ci-stolostron-multicluster-global-hub-main-test-unit/1716721252795682816#1:build-log.txt%3A1574
and 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stolostron_multicluster-global-hub/699/pull-ci-stolostron-multicluster-global-hub-main-test-unit/1716724914012033024#1:build-log.txt%3A1584

2023-10-27 00:44 UTC, ldpliu commented on test/pkg/e2e/grafana_test.go
> +			}, 2*time.Minute, 10*time.Second).ShouldNot(HaveOccurred())
In my test, it response very quickly.

2023-10-27 00:44 UTC, ldpliu commented on test/pkg/e2e/grafana_test.go
> +	url := "http://" + poList.Items[0].Status.PodIP + ":3001/api/" + path
Changed using kubectl exec to access the api

2023-10-30 06:37 UTC, clyang82 commented on test/pkg/e2e/grafana_test.go
> +			}, 2*time.Minute, 10*time.Second).ShouldNot(HaveOccurred())
that is my understand. why the interval is 10 seconds? maybe update to 1 second.

2023-10-30 06:37 UTC, clyang82 commented on test/pkg/e2e/grafana_test.go
> +		}, 2*time.Minute, 10*time.Second).ShouldNot(HaveOccurred())
update the 1 second to reduce the possible waiting time.

2023-10-30 06:45 UTC, clyang82 approved these changes
/lgtm

2023-10-30 07:18 UTC, merged