:bug: Wait until the resources is ready to start controller-manager
stolostron/multicluster-global-hub pull request #890
Opened 2024-04-16 03:53 UTC by yanmxa

## Summary

The controller runtime manager won't start if it watches a resource that hasn't existed since version 0.15.  So if we want to run the global hub operator under a bare kube environment. It needs to detect the necessary resources to be ready to start the manager. 

## Related issue(s)

Fixes #

2024-04-16 07:56 UTC, yanmxa commented
/hold

2024-04-17 01:12 UTC, clyang82 commented on operator/main.go
> +	if err := ResourceReady(ctx, cfg); err != nil {
in this case, the operator cannot be started without those resource. is it correct? if so, the CVP test cannot be passed with this fix.

2024-04-18 13:22 UTC, yanmxa commented
/retest

2024-04-22 02:01 UTC, yanmxa commented
/unhold

2024-04-22 02:17 UTC, yanmxa commented
/retest

2024-04-22 03:07 UTC, yanmxa commented
/retest

2024-04-22 03:16 UTC, yanmxa commented
/override ci/prow/sonarcloud
/override "SonarCloud Code Analysis"

2024-04-22 06:38 UTC, yanmxa commented
/cc @clyang82

2024-04-25 01:57 UTC, clyang82 requested changes
Did you test the operator in pure OpenShift cluster?

2024-04-25 01:57 UTC, clyang82 commented on operator/main.go
>  		&addonv1alpha1.ClusterManagementAddOn{}: {
`ClusterManagementAddOn` is ACM CRD. the operator cannot be started without it.

2024-04-25 01:57 UTC, clyang82 commented on operator/pkg/controllers/crd/crd_controller.go
> +		return ctrl.Result{}, nil
How can we dynamically update cache when those resources are ready?

2024-04-25 04:07 UTC, yanmxa commented on operator/main.go
>  		&addonv1alpha1.ClusterManagementAddOn{}: {
The `ClusterManagementAddOn` can be added to the cache when starting the manager. It only crashes when `Watch` a CRD resource that doesn't exist in the cluster.

2024-04-25 04:14 UTC, yanmxa commented on operator/pkg/controllers/crd/crd_controller.go
> +		return ctrl.Result{}, nil
It provides a lower method to update the cache when dynamically adding the controller to the manager, like: 
```go
.WatchesRawSource(source.Kind(installerCache, &clusterv1.ManagedCluster{}),
	&handler.EnqueueRequestForObject{}, builder.WithPredicates(clusterPred)).
```
However, the cache isn't the reason to break down the operator. Do we need to replace the manager cache with the lower interface?

2024-04-25 04:15 UTC, yanmxa commented
If the crd resources aren't ready. the operator will be running with the following log:
```bash
oc logs -f -l name=multicluster-global-hub-operator -n multicluster-global-hub
2024-04-18T05:25:41.385Z        INFO    setup   Go OS/Arch: linux/amd64
2024-04-18T05:25:41.402Z        INFO    setup   starting manager
2024-04-18T05:25:41.402Z        INFO    controller-runtime.metrics      Starting metrics server
2024-04-18T05:25:41.402Z        INFO    starting server {"kind": "health probe", "addr": "[::]:8081"}
2024-04-18T05:25:41.402Z        INFO    controller-runtime.metrics      Serving metrics server  {"bindAddress": ":8080", "secure": false}
I0418 05:25:41.402653       1 leaderelection.go:250] attempting to acquire leader lease multicluster-global-hub/multicluster-global-hub-operator-lock...
I0418 05:25:41.407270       1 leaderelection.go:260] successfully acquired lease multicluster-global-hub/multicluster-global-hub-operator-lock
2024-04-18T05:25:41.408Z        INFO    Starting EventSource    {"controller": "CRDController", "source": "kind source: *v1.PartialObjectMetadata"}
2024-04-18T05:25:41.408Z        INFO    Starting Controller     {"controller": "CRDController"}
2024-04-18T05:25:41.510Z        INFO    Starting workers        {"controller": "CRDController", "worker count": 1}
```

2024-04-25 07:35 UTC, yanmxa commented
/hold

2024-04-25 07:37 UTC, yanmxa commented
/hold

2024-04-25 08:17 UTC, yanmxa commented
> Did you test the operator in pure OpenShift cluster?

Yes. It works now.

2024-04-25 09:47 UTC, yanmxa commented on operator/pkg/controllers/crd/crd_controller.go
> +		return ctrl.Result{}, nil
I try to build a dynamic cache but It cannot work.
```bash
func ACMCache(mgr ctrl.Manager) (cache.Cache, error) {
	cacheOptions := cache.Options{
		Scheme: mgr.GetScheme(),
		Mapper: mgr.GetRESTMapper(),
	}
	cacheOptions.ByObject = map[client.Object]cache.ByObject{
		// addon installer, global hub controller
		&clusterv1.ManagedCluster{}: {
			Label: labels.SelectorFromSet(labels.Set{"vendor": "OpenShift"}),
		},
		// addon installer, global hub controller
		&addonv1alpha1.ClusterManagementAddOn{}: {
			Label: labelSelector,
		},
		// addon installer
		&addonv1alpha1.ManagedClusterAddOn{}: {
			Label: labelSelector,
		},
		// global hub controller
		&promv1.ServiceMonitor{}: {
			Label: labelSelector,
		},
		// global hub controller
		&subv1alpha1.Subscription{}: {},
	}
	extendCache, err := cache.New(mgr.GetConfig(), cacheOptions)
	if err != nil {
		return nil, err
	}
	return extendCache, err
}
```

2024-04-25 12:00 UTC, yanmxa commented
/retest

2024-04-25 13:20 UTC, yanmxa commented
/retest

2024-04-25 13:26 UTC, yanmxa commented
/retest

2024-04-25 13:31 UTC, yanmxa commented
override "ci/prow/sonarcloud"

2024-04-26 01:19 UTC, yanmxa commented
/override ci/prow/sonarcloud

2024-04-26 16:08 UTC, yanmxa commented
When start the operator in a OCP without ACM: 
```bash
root@myan workspace/hub-of-hubs (br_wait_ready) » oc logs -f -l name=multicluster-global-hub-operator -n multicluster-global-hub
2024-04-26T16:01:56.522Z        INFO    setup   Go OS/Arch: linux/amd64
2024-04-26T16:01:56.540Z        INFO    setup   starting manager
2024-04-26T16:01:56.540Z        INFO    controller-runtime.metrics      Starting metrics server
2024-04-26T16:01:56.540Z        INFO    starting server {"kind": "health probe", "addr": "[::]:8081"}
2024-04-26T16:01:56.540Z        INFO    controller-runtime.metrics      Serving metrics server  {"bindAddress": ":8080", "secure": false}
I0426 16:01:56.540571       1 leaderelection.go:250] attempting to acquire leader lease multicluster-global-hub/multicluster-global-hub-operator-lock...
I0426 16:01:56.545371       1 leaderelection.go:260] successfully acquired lease multicluster-global-hub/multicluster-global-hub-operator-lock
2024-04-26T16:01:56.545Z        INFO    Starting EventSource    {"controller": "CRDController", "source": "kind source: *v1.PartialObjectMetadata"}
2024-04-26T16:01:56.545Z        INFO    Starting Controller     {"controller": "CRDController"}
2024-04-26T16:01:56.646Z        INFO    Starting workers        {"controller": "CRDController", "worker count": 1}
```

2024-04-26 16:10 UTC, yanmxa commented
After installing ACM. It will start all the other controllers:
```bash
I0426 16:07:29.302458       1 utils.go:241] Wait MulticlusterGlobalHub created
2024-04-26T16:07:29.302Z        INFO    Starting EventSource    {"controller": "addonInstaller", "source": "kind source: *v1.ManagedCluster"}
2024-04-26T16:07:29.302Z        INFO    Starting EventSource    {"controller": "addonInstaller", "source": "kind source: *v1alpha1.ManagedClusterAddOn"}
2024-04-26T16:07:29.302Z        INFO    Starting EventSource    {"controller": "addonInstaller", "source": "kind source: *v1alpha1.ClusterManagementAddOn"}
2024-04-26T16:07:29.302Z        INFO    Starting EventSource    {"controller": "addonInstaller", "source": "kind source: *v1.Secret"}
2024-04-26T16:07:29.302Z        INFO    Starting Controller     {"controller": "addonInstaller"}
2024-04-26T16:07:29.303Z        INFO    Starting Controller     {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub"}
2024-04-26T16:07:29.303Z        INFO    Starting workers        {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "worker count": 1}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "conditionController", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1alpha4.MulticlusterGlobalHub"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "conditionController", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Deployment"}
2024-04-26T16:07:29.303Z        INFO    Starting Controller     {"controller": "conditionController", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1alpha4.MulticlusterGlobalHub"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Deployment"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.StatefulSet"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Service"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.ServiceAccount"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Secret"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Role"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.RoleBinding"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Route"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.MutatingWebhookConfiguration"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.ConfigMap"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Namespace"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.ClusterRole"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.ClusterRoleBinding"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Secret"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1alpha1.ClusterManagementAddOn"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.ManagedCluster"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.ServiceMonitor"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1alpha1.Subscription"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "backupController", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1alpha4.MulticlusterGlobalHub"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "backupController", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.Secret"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "backupController", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.ConfigMap"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "backupController", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.PersistentVolumeClaim"}
2024-04-26T16:07:29.303Z        INFO    Starting EventSource    {"controller": "backupController", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "source": "kind source: *v1.MultiClusterHub"}
2024-04-26T16:07:29.303Z        INFO    Starting Controller      [...]

2024-04-28 03:26 UTC, clyang82 approved these changes
Perfect

2024-04-28 03:30 UTC, merged