:seedling: Persistent the agent event state to the configmap
stolostron/multicluster-global-hub pull request #899
Opened 2024-04-24 14:40 UTC by yanmxa

## Summary

Add the configMap to save the agent event state, so as to deduplicate the event in the message queue(event topics)

## Related issue(s)

Fixes #

2024-04-25 06:56 UTC, yanmxa commented
/retest

2024-04-25 07:34 UTC, yanmxa commented
/cc @clyang82 @ldpliu

2024-04-26 03:05 UTC, yanmxa commented
/retest

2024-04-26 09:48 UTC, yanmxa commented
/retest

2024-04-26 11:22 UTC, clyang82 requested changes

2024-04-26 11:22 UTC, clyang82 commented on agent/pkg/status/controller/event/local_replicated_policy_emitter.go
> +			CreatedAt:      evt.LastTimestamp,
what is the difference for those two timestamp?

2024-04-26 11:22 UTC, clyang82 commented on agent/pkg/status/controller/filter/time_filter.go
> +		if e := c.Create(ctx, agentStateConfigMap); e != nil {
do we need to add create permission?

2024-04-26 11:22 UTC, clyang82 commented on agent/pkg/status/controller/filter/time_filter.go
> +func loadTimeCacheFromConfigMap(cm *corev1.ConfigMap, key string) error {
maybe `loadEventTimeCacheFromConfigmap`

2024-04-26 11:22 UTC, clyang82 commented on agent/pkg/status/controller/filter/time_filter.go
> +// RegisterTimeFilter call before the LaunchTimeFilter, it will get the init time from the configMap
i saw you just initiate the map.  Do you need to get from the configmap? i think we need

2024-04-26 16:30 UTC, yanmxa commented on agent/pkg/status/controller/event/local_replicated_policy_emitter.go
> +			CreatedAt:      evt.LastTimestamp,
`CreationTimestamp` is from [ObjectMeta](https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/common-definitions/object-meta/). It indicates [when the object is created](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).

`LastTimestamp` is the [time](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L6646) at which the most recent occurrence of this event was recorded. 

From the above description, we can see that the event can only be created once, meaning it cannot be changed even if it is updated. So instead of using `CreationTimestamp`, I choose the `LastTimestamp` as the unique event identifier for the time filter.

2024-04-26 16:33 UTC, yanmxa commented on agent/pkg/status/controller/filter/time_filter.go
> +		if e := c.Create(ctx, agentStateConfigMap); e != nil {
We already have the create permission. 
https://github.com/stolostron/multicluster-global-hub/blob/main/operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml#L97-L101

2024-04-26 16:45 UTC, yanmxa commented on agent/pkg/status/controller/filter/time_filter.go
> +// RegisterTimeFilter call before the LaunchTimeFilter, it will get the init time from the configMap
It inits the map with an empty collection and restores value from the confgmap. 

I'm okay to init and restore value on `LaunchTimeFilter` if you think it is necessary.

2024-04-26 16:45 UTC, yanmxa commented on agent/pkg/status/controller/filter/time_filter.go
> +func loadTimeCacheFromConfigMap(cm *corev1.ConfigMap, key string) error {
Done.

2024-04-26 16:47 UTC, yanmxa commented
/retest ci/prow/gofmt

2024-04-26 16:47 UTC, yanmxa commented
/test gofmt

2024-04-28 01:33 UTC, yanmxa commented
/test test-e2e

2024-05-08 06:56 UTC, clyang82 commented on agent/pkg/status/controller/event/local_replicated_policy_emitter.go
> +			CreatedAt:      evt.LastTimestamp,
I think we should keep using `CreationTimestamp`. To my understand, the `CreationTimestamp` is for real creation for this event. sometimes, the `firstTimestamp` and `lastTimestamp` are not set. Again, if the events have emitted in multiple times, the `firstTimestamp` and `lastTimestamp` are meaningful.
```
- action: DecisionUpdated
  apiVersion: v1
  eventTime: "2024-05-08T06:44:04.303377Z"
  firstTimestamp: null
  involvedObject:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: global
    namespace: open-cluster-management-global-set
    resourceVersion: "149108"
    uid: 92f660b0-5383-43eb-a10d-429e946cdc5c
  kind: Event
  lastTimestamp: null
  message: Decision global-decision-1 is updated with placement global in namespace
    open-cluster-management-global-set
  metadata:
    creationTimestamp: "2024-05-08T06:44:04Z"
    name: global.17cd706c79fc438f
    namespace: open-cluster-management-global-set
    resourceVersion: "12338614"
    uid: 8fd3c9d7-2771-440f-bf70-0d6df20912b5
  reason: DecisionUpdate
  related:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: PlacementDecision
    name: global-decision-1
    namespace: open-cluster-management-global-set
    resourceVersion: "149105"
    uid: ceddbd89-d04a-4203-b006-94756be2e3bd
  reportingComponent: placementController
  reportingInstance: placementController-cluster-manager-placement-controller-6c8b7cf458-5xb8s
  series:
    count: 6
    lastObservedTime: "2024-05-08T06:44:12.674112Z"
  source: {}
  type: Normal
```

2024-05-08 13:32 UTC, yanmxa commented on agent/pkg/status/controller/event/local_replicated_policy_emitter.go
> +			CreatedAt:      evt.LastTimestamp,
Yes. The other timestamp might be empty. Use the `creationTimestamp` back

2024-05-09 01:14 UTC, clyang82 approved these changes
LGTM

2024-05-09 01:30 UTC, yanmxa commented
/test test-unit

2024-05-09 03:08 UTC, yanmxa commented
/test test-e2e

2024-05-09 04:06 UTC, yanmxa commented
/test test-unit

2024-05-09 04:15 UTC, merged