update topic replica to 3
stolostron/multicluster-global-hub pull request #905
Opened 2024-04-30 00:53 UTC by ldpliu

## Summary
As we discussed in meeting, we should update the topic replica to 3.
## Related issue(s)

Fixes #

2024-04-30 01:06 UTC, ldpliu commented
/retest

2024-04-30 01:27 UTC, ldpliu commented
/retest

2024-04-30 02:17 UTC, ldpliu commented
/retest

2024-04-30 04:44 UTC, yanmxa commented on operator/pkg/transporter/strimzi_transporter.go
> +		if !reflect.DeepEqual(desiredTopic.Spec.Replicas, kafkaTopic.Spec.Replicas) {
If we only assert the replicas, maybe we don't need the `reflect.DeepEqual` method

2024-04-30 06:04 UTC, ldpliu commented on operator/pkg/transporter/strimzi_transporter.go
> +		if !reflect.DeepEqual(desiredTopic.Spec.Replicas, kafkaTopic.Spec.Replicas) {
> If we only assert the replicas, maybe we don't need the `reflect.DeepEqual` method

Changed.

2024-04-30 06:06 UTC, ldpliu commented
/cc @yanmxa @clyang82

2024-05-06 08:54 UTC, clyang82 requested changes
Need to update the document for the storage size

2024-05-08 03:35 UTC, clyang82 commented on operator/pkg/transporter/strimzi_transporter.go
> +		desiredTopic := k.newKafkaTopic(topicName)
after inner discussion, we agree to reconcile the kafkatopic and kafkauser. in other words, we do not allow the user to modify the kafkatopic and kafkauser. @hchenxa @yahliu any concerns for this behaviour change?

2024-05-08 13:04 UTC, clyang82 approved these changes
LGTM

2024-05-08 23:58 UTC, ldpliu commented
/retest

2024-05-09 00:08 UTC, merged