:bug: Fix the event format `incompatible` when upgrading
stolostron/multicluster-global-hub pull request #910
Opened 2024-05-07 10:05 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>

## Summary

## Related issue(s)

Fixes # https://issues.redhat.com/browse/ACM-11490

2024-05-07 10:09 UTC, yanmxa commented
/cc @clyang82 @ldpliu

2024-05-08 03:55 UTC, clyang82 requested changes

2024-05-08 03:55 UTC, clyang82 commented on agent/pkg/spec/controller/syncers/dispatcher.go
> +				d.log.Info("nil syncer or evt", "syncer", syncer, "event", evt)
enhance the message to mention that this info is an intermediate message, once the manager is upgraded successfully, the message will be disappeared.

2024-05-08 07:11 UTC, yanmxa commented on agent/pkg/spec/controller/syncers/dispatcher.go
> +				d.log.Info("nil syncer or evt", "syncer", syncer, "event", evt)
Done.

2024-05-08 07:12 UTC, yanmxa commented
/retest

2024-05-08 08:44 UTC, clyang82 approved these changes
LGTM

2024-05-08 09:21 UTC, merged