:bug: fix some dashboard error
stolostron/multicluster-global-hub pull request #954
Opened 2024-06-04 01:55 UTC by ldpliu

## Summary

## Related issue(s)

Fixes #

2024-06-04 23:13 UTC, ldpliu commented
/retest

2024-06-07 03:31 UTC, clyang82 requested changes

2024-06-07 03:31 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml
> +              "text": " in ('mc1') ",
hardcode `mc1`?

2024-06-07 03:31 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml
> +              "text": " in ('mc2') ",
should not have `mc2`. right?

2024-06-07 03:31 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres.yaml
> +              "text": "10.128.1.164:9187",
ditto

2024-06-07 05:58 UTC, ldpliu commented on operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml
> +              "text": " in ('mc1') ",
It doesn't matter if this value is set or not. It will be reloaded in the real env.

2024-06-07 06:02 UTC, clyang82 approved these changes
LGTM

2024-06-07 06:02 UTC, clyang82 commented
/override ci/prow/test-e2e

2024-06-07 06:07 UTC, merged